// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: availability.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTeacherAvailability = `-- name: DeleteTeacherAvailability :exec
DELETE FROM hr.teacher_availability WHERE teacher_id = $1
`

func (q *Queries) DeleteTeacherAvailability(ctx context.Context, teacherID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeacherAvailability, teacherID)
	return err
}

const listTeacherAvailability = `-- name: ListTeacherAvailability :many
SELECT id, teacher_id, day_of_week, start_period, end_period FROM hr.teacher_availability
WHERE teacher_id = $1
ORDER BY day_of_week, start_period
`

func (q *Queries) ListTeacherAvailability(ctx context.Context, teacherID pgtype.UUID) ([]HrTeacherAvailability, error) {
	rows, err := q.db.Query(ctx, listTeacherAvailability, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrTeacherAvailability
	for rows.Next() {
		var i HrTeacherAvailability
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.DayOfWeek,
			&i.StartPeriod,
			&i.EndPeriod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAvailabilitySlot = `-- name: UpsertAvailabilitySlot :one
INSERT INTO hr.teacher_availability (teacher_id, day_of_week, start_period, end_period)
VALUES ($1, $2, $3, $4)
ON CONFLICT (teacher_id, day_of_week, start_period)
DO UPDATE SET end_period = EXCLUDED.end_period
RETURNING id, teacher_id, day_of_week, start_period, end_period
`

type UpsertAvailabilitySlotParams struct {
	TeacherID   pgtype.UUID `json:"teacher_id"`
	DayOfWeek   int32       `json:"day_of_week"`
	StartPeriod int32       `json:"start_period"`
	EndPeriod   int32       `json:"end_period"`
}

func (q *Queries) UpsertAvailabilitySlot(ctx context.Context, arg UpsertAvailabilitySlotParams) (HrTeacherAvailability, error) {
	row := q.db.QueryRow(ctx, upsertAvailabilitySlot,
		arg.TeacherID,
		arg.DayOfWeek,
		arg.StartPeriod,
		arg.EndPeriod,
	)
	var i HrTeacherAvailability
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.DayOfWeek,
		&i.StartPeriod,
		&i.EndPeriod,
	)
	return i, err
}
