// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: departments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDepartments = `-- name: CountDepartments :one
SELECT COUNT(*) FROM hr.departments
`

func (q *Queries) CountDepartments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDepartments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO hr.departments (name, code)
VALUES ($1, $2) RETURNING id, name, code, created_at, updated_at
`

type CreateDepartmentParams struct {
	Name string `json:"name"`
	Code string `json:"code"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (HrDepartment, error) {
	row := q.db.QueryRow(ctx, createDepartment, arg.Name, arg.Code)
	var i HrDepartment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepartmentByID = `-- name: GetDepartmentByID :one
SELECT id, name, code, created_at, updated_at FROM hr.departments WHERE id = $1
`

func (q *Queries) GetDepartmentByID(ctx context.Context, id pgtype.UUID) (HrDepartment, error) {
	row := q.db.QueryRow(ctx, getDepartmentByID, id)
	var i HrDepartment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, name, code, created_at, updated_at FROM hr.departments ORDER BY name LIMIT $1 OFFSET $2
`

type ListDepartmentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDepartments(ctx context.Context, arg ListDepartmentsParams) ([]HrDepartment, error) {
	rows, err := q.db.Query(ctx, listDepartments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrDepartment
	for rows.Next() {
		var i HrDepartment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
