// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type HrDepartment struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Code      string             `json:"code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type HrEvent struct {
	ID            int64              `json:"id"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	AggregateType string             `json:"aggregate_type"`
	EventType     string             `json:"event_type"`
	Version       int32              `json:"version"`
	Data          []byte             `json:"data"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type HrSnapshot struct {
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	AggregateType string             `json:"aggregate_type"`
	Version       int32              `json:"version"`
	Data          []byte             `json:"data"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type HrTeacher struct {
	ID              pgtype.UUID        `json:"id"`
	EmployeeCode    string             `json:"employee_code"`
	FullName        string             `json:"full_name"`
	Email           string             `json:"email"`
	Phone           pgtype.Text        `json:"phone"`
	DepartmentID    pgtype.UUID        `json:"department_id"`
	MaxHoursPerWeek int32              `json:"max_hours_per_week"`
	Title           pgtype.Text        `json:"title"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type HrTeacherAvailability struct {
	ID          pgtype.UUID `json:"id"`
	TeacherID   pgtype.UUID `json:"teacher_id"`
	DayOfWeek   int32       `json:"day_of_week"`
	StartPeriod int32       `json:"start_period"`
	EndPeriod   int32       `json:"end_period"`
}

type HrTeacherSpecialization struct {
	TeacherID      pgtype.UUID `json:"teacher_id"`
	Specialization string      `json:"specialization"`
}
