// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddSpecialization(ctx context.Context, arg AddSpecializationParams) error
	CountDepartments(ctx context.Context) (int64, error)
	CountTeachers(ctx context.Context) (int64, error)
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (HrDepartment, error)
	CreateTeacher(ctx context.Context, arg CreateTeacherParams) (HrTeacher, error)
	DeleteTeacher(ctx context.Context, id pgtype.UUID) error
	DeleteTeacherAvailability(ctx context.Context, teacherID pgtype.UUID) error
	GetDepartmentByID(ctx context.Context, id pgtype.UUID) (HrDepartment, error)
	GetTeacherByID(ctx context.Context, id pgtype.UUID) (HrTeacher, error)
	ListDepartments(ctx context.Context, arg ListDepartmentsParams) ([]HrDepartment, error)
	ListSpecializations(ctx context.Context, teacherID pgtype.UUID) ([]string, error)
	ListTeacherAvailability(ctx context.Context, teacherID pgtype.UUID) ([]HrTeacherAvailability, error)
	ListTeachers(ctx context.Context, arg ListTeachersParams) ([]HrTeacher, error)
	ListTeachersByDepartment(ctx context.Context, arg ListTeachersByDepartmentParams) ([]HrTeacher, error)
	RemoveSpecialization(ctx context.Context, arg RemoveSpecializationParams) error
	SearchTeachersByName(ctx context.Context, arg SearchTeachersByNameParams) ([]HrTeacher, error)
	SearchTeachersBySpecialization(ctx context.Context, specialization string) ([]HrTeacher, error)
	UpdateTeacher(ctx context.Context, arg UpdateTeacherParams) (HrTeacher, error)
	UpsertAvailabilitySlot(ctx context.Context, arg UpsertAvailabilitySlotParams) (HrTeacherAvailability, error)
}

var _ Querier = (*Queries)(nil)
