// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teachers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addSpecialization = `-- name: AddSpecialization :exec
INSERT INTO hr.teacher_specializations (teacher_id, specialization)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddSpecializationParams struct {
	TeacherID      pgtype.UUID `json:"teacher_id"`
	Specialization string      `json:"specialization"`
}

func (q *Queries) AddSpecialization(ctx context.Context, arg AddSpecializationParams) error {
	_, err := q.db.Exec(ctx, addSpecialization, arg.TeacherID, arg.Specialization)
	return err
}

const countTeachers = `-- name: CountTeachers :one
SELECT COUNT(*) FROM hr.teachers WHERE is_active = true
`

func (q *Queries) CountTeachers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTeachers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTeacher = `-- name: CreateTeacher :one
INSERT INTO hr.teachers (employee_code, full_name, email, phone, department_id, max_hours_per_week, title)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, employee_code, full_name, email, phone, department_id, max_hours_per_week, title, is_active, created_at, updated_at
`

type CreateTeacherParams struct {
	EmployeeCode    string      `json:"employee_code"`
	FullName        string      `json:"full_name"`
	Email           string      `json:"email"`
	Phone           pgtype.Text `json:"phone"`
	DepartmentID    pgtype.UUID `json:"department_id"`
	MaxHoursPerWeek int32       `json:"max_hours_per_week"`
	Title           pgtype.Text `json:"title"`
}

func (q *Queries) CreateTeacher(ctx context.Context, arg CreateTeacherParams) (HrTeacher, error) {
	row := q.db.QueryRow(ctx, createTeacher,
		arg.EmployeeCode,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.DepartmentID,
		arg.MaxHoursPerWeek,
		arg.Title,
	)
	var i HrTeacher
	err := row.Scan(
		&i.ID,
		&i.EmployeeCode,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.DepartmentID,
		&i.MaxHoursPerWeek,
		&i.Title,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeacher = `-- name: DeleteTeacher :exec
UPDATE hr.teachers SET is_active = false, updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeleteTeacher(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeacher, id)
	return err
}

const getTeacherByID = `-- name: GetTeacherByID :one
SELECT id, employee_code, full_name, email, phone, department_id, max_hours_per_week, title, is_active, created_at, updated_at FROM hr.teachers WHERE id = $1
`

func (q *Queries) GetTeacherByID(ctx context.Context, id pgtype.UUID) (HrTeacher, error) {
	row := q.db.QueryRow(ctx, getTeacherByID, id)
	var i HrTeacher
	err := row.Scan(
		&i.ID,
		&i.EmployeeCode,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.DepartmentID,
		&i.MaxHoursPerWeek,
		&i.Title,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSpecializations = `-- name: ListSpecializations :many
SELECT specialization FROM hr.teacher_specializations WHERE teacher_id = $1
`

func (q *Queries) ListSpecializations(ctx context.Context, teacherID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listSpecializations, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var specialization string
		if err := rows.Scan(&specialization); err != nil {
			return nil, err
		}
		items = append(items, specialization)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeachers = `-- name: ListTeachers :many
SELECT id, employee_code, full_name, email, phone, department_id, max_hours_per_week, title, is_active, created_at, updated_at FROM hr.teachers WHERE is_active = true ORDER BY full_name LIMIT $1 OFFSET $2
`

type ListTeachersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTeachers(ctx context.Context, arg ListTeachersParams) ([]HrTeacher, error) {
	rows, err := q.db.Query(ctx, listTeachers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrTeacher
	for rows.Next() {
		var i HrTeacher
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeCode,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.DepartmentID,
			&i.MaxHoursPerWeek,
			&i.Title,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeachersByDepartment = `-- name: ListTeachersByDepartment :many
SELECT id, employee_code, full_name, email, phone, department_id, max_hours_per_week, title, is_active, created_at, updated_at FROM hr.teachers WHERE department_id = $1 AND is_active = true ORDER BY full_name LIMIT $2 OFFSET $3
`

type ListTeachersByDepartmentParams struct {
	DepartmentID pgtype.UUID `json:"department_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

func (q *Queries) ListTeachersByDepartment(ctx context.Context, arg ListTeachersByDepartmentParams) ([]HrTeacher, error) {
	rows, err := q.db.Query(ctx, listTeachersByDepartment, arg.DepartmentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrTeacher
	for rows.Next() {
		var i HrTeacher
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeCode,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.DepartmentID,
			&i.MaxHoursPerWeek,
			&i.Title,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSpecialization = `-- name: RemoveSpecialization :exec
DELETE FROM hr.teacher_specializations WHERE teacher_id = $1 AND specialization = $2
`

type RemoveSpecializationParams struct {
	TeacherID      pgtype.UUID `json:"teacher_id"`
	Specialization string      `json:"specialization"`
}

func (q *Queries) RemoveSpecialization(ctx context.Context, arg RemoveSpecializationParams) error {
	_, err := q.db.Exec(ctx, removeSpecialization, arg.TeacherID, arg.Specialization)
	return err
}

const searchTeachersByName = `-- name: SearchTeachersByName :many
SELECT id, employee_code, full_name, email, phone, department_id, max_hours_per_week, title, is_active, created_at, updated_at FROM hr.teachers
WHERE full_name ILIKE '%' || $1 || '%' AND is_active = true
ORDER BY full_name LIMIT $2 OFFSET $3
`

type SearchTeachersByNameParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) SearchTeachersByName(ctx context.Context, arg SearchTeachersByNameParams) ([]HrTeacher, error) {
	rows, err := q.db.Query(ctx, searchTeachersByName, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrTeacher
	for rows.Next() {
		var i HrTeacher
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeCode,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.DepartmentID,
			&i.MaxHoursPerWeek,
			&i.Title,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTeachersBySpecialization = `-- name: SearchTeachersBySpecialization :many
SELECT t.id, t.employee_code, t.full_name, t.email, t.phone, t.department_id, t.max_hours_per_week, t.title, t.is_active, t.created_at, t.updated_at FROM hr.teachers t
JOIN hr.teacher_specializations ts ON t.id = ts.teacher_id
WHERE ts.specialization = $1 AND t.is_active = true
ORDER BY t.full_name
`

func (q *Queries) SearchTeachersBySpecialization(ctx context.Context, specialization string) ([]HrTeacher, error) {
	rows, err := q.db.Query(ctx, searchTeachersBySpecialization, specialization)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrTeacher
	for rows.Next() {
		var i HrTeacher
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeCode,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.DepartmentID,
			&i.MaxHoursPerWeek,
			&i.Title,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeacher = `-- name: UpdateTeacher :one
UPDATE hr.teachers
SET full_name = $2, email = $3, phone = $4, department_id = $5,
    max_hours_per_week = $6, title = $7, is_active = $8, updated_at = NOW()
WHERE id = $1 RETURNING id, employee_code, full_name, email, phone, department_id, max_hours_per_week, title, is_active, created_at, updated_at
`

type UpdateTeacherParams struct {
	ID              pgtype.UUID `json:"id"`
	FullName        string      `json:"full_name"`
	Email           string      `json:"email"`
	Phone           pgtype.Text `json:"phone"`
	DepartmentID    pgtype.UUID `json:"department_id"`
	MaxHoursPerWeek int32       `json:"max_hours_per_week"`
	Title           pgtype.Text `json:"title"`
	IsActive        bool        `json:"is_active"`
}

func (q *Queries) UpdateTeacher(ctx context.Context, arg UpdateTeacherParams) (HrTeacher, error) {
	row := q.db.QueryRow(ctx, updateTeacher,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.DepartmentID,
		arg.MaxHoursPerWeek,
		arg.Title,
		arg.IsActive,
	)
	var i HrTeacher
	err := row.Scan(
		&i.ID,
		&i.EmployeeCode,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.DepartmentID,
		&i.MaxHoursPerWeek,
		&i.Title,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
