// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// SubjectSubject maps to subject.subjects table.
type SubjectSubject struct {
	ID           pgtype.UUID        `json:"id"`
	Code         string             `json:"code"`
	Name         string             `json:"name"`
	Credits      int32              `json:"credits"`
	Description  string             `json:"description"`
	DepartmentID string             `json:"department_id"`
	WeeklyHours  int32              `json:"weekly_hours"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// SubjectPrerequisite maps to subject.prerequisites table.
type SubjectPrerequisite struct {
	SubjectID      pgtype.UUID `json:"subject_id"`
	PrerequisiteID pgtype.UUID `json:"prerequisite_id"`
	Type           string      `json:"type"`
	Priority       int32       `json:"priority"`
}

// SubjectSemesterOffering maps to subject.semester_offerings table.
type SubjectSemesterOffering struct {
	ID            pgtype.UUID        `json:"id"`
	SubjectID     pgtype.UUID        `json:"subject_id"`
	SemesterID    pgtype.UUID        `json:"semester_id"`
	MaxEnrollment int32              `json:"max_enrollment"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
