// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prerequisites.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPrerequisite = `-- name: AddPrerequisite :one
INSERT INTO subject.prerequisites (subject_id, prerequisite_id, type, priority)
VALUES ($1, $2, $3, $4) RETURNING subject_id, prerequisite_id, type, priority
`

type AddPrerequisiteParams struct {
	SubjectID      pgtype.UUID `json:"subject_id"`
	PrerequisiteID pgtype.UUID `json:"prerequisite_id"`
	Type           string      `json:"type"`
	Priority       int32       `json:"priority"`
}

func (q *Queries) AddPrerequisite(ctx context.Context, arg AddPrerequisiteParams) (SubjectPrerequisite, error) {
	row := q.db.QueryRow(ctx, addPrerequisite,
		arg.SubjectID, arg.PrerequisiteID, arg.Type, arg.Priority,
	)
	var i SubjectPrerequisite
	err := row.Scan(&i.SubjectID, &i.PrerequisiteID, &i.Type, &i.Priority)
	return i, err
}

const removePrerequisite = `-- name: RemovePrerequisite :exec
DELETE FROM subject.prerequisites WHERE subject_id = $1 AND prerequisite_id = $2
`

func (q *Queries) RemovePrerequisite(ctx context.Context, subjectID, prerequisiteID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removePrerequisite, subjectID, prerequisiteID)
	return err
}

const listPrerequisitesBySubject = `-- name: ListPrerequisitesBySubject :many
SELECT subject_id, prerequisite_id, type, priority FROM subject.prerequisites WHERE subject_id = $1 ORDER BY priority ASC
`

func (q *Queries) ListPrerequisitesBySubject(ctx context.Context, subjectID pgtype.UUID) ([]SubjectPrerequisite, error) {
	rows, err := q.db.Query(ctx, listPrerequisitesBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubjectPrerequisite
	for rows.Next() {
		var i SubjectPrerequisite
		if err := rows.Scan(&i.SubjectID, &i.PrerequisiteID, &i.Type, &i.Priority); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listAllPrerequisites = `-- name: ListAllPrerequisites :many
SELECT subject_id, prerequisite_id, type, priority FROM subject.prerequisites ORDER BY subject_id, priority ASC
`

func (q *Queries) ListAllPrerequisites(ctx context.Context) ([]SubjectPrerequisite, error) {
	rows, err := q.db.Query(ctx, listAllPrerequisites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubjectPrerequisite
	for rows.Next() {
		var i SubjectPrerequisite
		if err := rows.Scan(&i.SubjectID, &i.PrerequisiteID, &i.Type, &i.Priority); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getPrerequisite = `-- name: GetPrerequisite :one
SELECT subject_id, prerequisite_id, type, priority FROM subject.prerequisites WHERE subject_id = $1 AND prerequisite_id = $2
`

func (q *Queries) GetPrerequisite(ctx context.Context, subjectID, prerequisiteID pgtype.UUID) (SubjectPrerequisite, error) {
	row := q.db.QueryRow(ctx, getPrerequisite, subjectID, prerequisiteID)
	var i SubjectPrerequisite
	err := row.Scan(&i.SubjectID, &i.PrerequisiteID, &i.Type, &i.Priority)
	return i, err
}
