// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: semester_offerings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSemesterOffering = `-- name: CreateSemesterOffering :one
INSERT INTO subject.semester_offerings (subject_id, semester_id, max_enrollment)
VALUES ($1, $2, $3) RETURNING id, subject_id, semester_id, max_enrollment, created_at
`

type CreateSemesterOfferingParams struct {
	SubjectID     pgtype.UUID `json:"subject_id"`
	SemesterID    pgtype.UUID `json:"semester_id"`
	MaxEnrollment int32       `json:"max_enrollment"`
}

func (q *Queries) CreateSemesterOffering(ctx context.Context, arg CreateSemesterOfferingParams) (SubjectSemesterOffering, error) {
	row := q.db.QueryRow(ctx, createSemesterOffering, arg.SubjectID, arg.SemesterID, arg.MaxEnrollment)
	var i SubjectSemesterOffering
	err := row.Scan(&i.ID, &i.SubjectID, &i.SemesterID, &i.MaxEnrollment, &i.CreatedAt)
	return i, err
}

const listSemesterOfferingsBySubject = `-- name: ListSemesterOfferingsBySubject :many
SELECT id, subject_id, semester_id, max_enrollment, created_at FROM subject.semester_offerings WHERE subject_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSemesterOfferingsBySubject(ctx context.Context, subjectID pgtype.UUID) ([]SubjectSemesterOffering, error) {
	rows, err := q.db.Query(ctx, listSemesterOfferingsBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubjectSemesterOffering
	for rows.Next() {
		var i SubjectSemesterOffering
		if err := rows.Scan(&i.ID, &i.SubjectID, &i.SemesterID, &i.MaxEnrollment, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getSemesterOffering = `-- name: GetSemesterOffering :one
SELECT id, subject_id, semester_id, max_enrollment, created_at FROM subject.semester_offerings WHERE id = $1
`

func (q *Queries) GetSemesterOffering(ctx context.Context, id pgtype.UUID) (SubjectSemesterOffering, error) {
	row := q.db.QueryRow(ctx, getSemesterOffering, id)
	var i SubjectSemesterOffering
	err := row.Scan(&i.ID, &i.SubjectID, &i.SemesterID, &i.MaxEnrollment, &i.CreatedAt)
	return i, err
}

const deleteSemesterOffering = `-- name: DeleteSemesterOffering :exec
DELETE FROM subject.semester_offerings WHERE id = $1
`

func (q *Queries) DeleteSemesterOffering(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSemesterOffering, id)
	return err
}
