// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subjects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubject = `-- name: CreateSubject :one
INSERT INTO subject.subjects (code, name, credits, description, department_id, weekly_hours, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, code, name, credits, description, department_id, weekly_hours, is_active, created_at, updated_at
`

type CreateSubjectParams struct {
	Code         string `json:"code"`
	Name         string `json:"name"`
	Credits      int32  `json:"credits"`
	Description  string `json:"description"`
	DepartmentID string `json:"department_id"`
	WeeklyHours  int32  `json:"weekly_hours"`
	IsActive     bool   `json:"is_active"`
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (SubjectSubject, error) {
	row := q.db.QueryRow(ctx, createSubject,
		arg.Code, arg.Name, arg.Credits, arg.Description, arg.DepartmentID, arg.WeeklyHours, arg.IsActive,
	)
	var i SubjectSubject
	err := row.Scan(
		&i.ID, &i.Code, &i.Name, &i.Credits, &i.Description,
		&i.DepartmentID, &i.WeeklyHours, &i.IsActive, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const getSubjectByID = `-- name: GetSubjectByID :one
SELECT id, code, name, credits, description, department_id, weekly_hours, is_active, created_at, updated_at FROM subject.subjects WHERE id = $1
`

func (q *Queries) GetSubjectByID(ctx context.Context, id pgtype.UUID) (SubjectSubject, error) {
	row := q.db.QueryRow(ctx, getSubjectByID, id)
	var i SubjectSubject
	err := row.Scan(
		&i.ID, &i.Code, &i.Name, &i.Credits, &i.Description,
		&i.DepartmentID, &i.WeeklyHours, &i.IsActive, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const getSubjectByCode = `-- name: GetSubjectByCode :one
SELECT id, code, name, credits, description, department_id, weekly_hours, is_active, created_at, updated_at FROM subject.subjects WHERE code = $1
`

func (q *Queries) GetSubjectByCode(ctx context.Context, code string) (SubjectSubject, error) {
	row := q.db.QueryRow(ctx, getSubjectByCode, code)
	var i SubjectSubject
	err := row.Scan(
		&i.ID, &i.Code, &i.Name, &i.Credits, &i.Description,
		&i.DepartmentID, &i.WeeklyHours, &i.IsActive, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const listSubjects = `-- name: ListSubjects :many
SELECT id, code, name, credits, description, department_id, weekly_hours, is_active, created_at, updated_at FROM subject.subjects ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListSubjectsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSubjects(ctx context.Context, arg ListSubjectsParams) ([]SubjectSubject, error) {
	rows, err := q.db.Query(ctx, listSubjects, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubjectSubject
	for rows.Next() {
		var i SubjectSubject
		if err := rows.Scan(
			&i.ID, &i.Code, &i.Name, &i.Credits, &i.Description,
			&i.DepartmentID, &i.WeeklyHours, &i.IsActive, &i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listSubjectsByDepartment = `-- name: ListSubjectsByDepartment :many
SELECT id, code, name, credits, description, department_id, weekly_hours, is_active, created_at, updated_at FROM subject.subjects WHERE department_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListSubjectsByDepartmentParams struct {
	DepartmentID string `json:"department_id"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
}

func (q *Queries) ListSubjectsByDepartment(ctx context.Context, arg ListSubjectsByDepartmentParams) ([]SubjectSubject, error) {
	rows, err := q.db.Query(ctx, listSubjectsByDepartment, arg.DepartmentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubjectSubject
	for rows.Next() {
		var i SubjectSubject
		if err := rows.Scan(
			&i.ID, &i.Code, &i.Name, &i.Credits, &i.Description,
			&i.DepartmentID, &i.WeeklyHours, &i.IsActive, &i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const countSubjects = `-- name: CountSubjects :one
SELECT COUNT(*) FROM subject.subjects
`

func (q *Queries) CountSubjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSubjects)
	var count int64
	return count, row.Scan(&count)
}

const countSubjectsByDepartment = `-- name: CountSubjectsByDepartment :one
SELECT COUNT(*) FROM subject.subjects WHERE department_id = $1
`

func (q *Queries) CountSubjectsByDepartment(ctx context.Context, departmentID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSubjectsByDepartment, departmentID)
	var count int64
	return count, row.Scan(&count)
}

const updateSubject = `-- name: UpdateSubject :one
UPDATE subject.subjects
SET code         = COALESCE($1, code),
    name         = COALESCE($2, name),
    credits      = COALESCE($3, credits),
    description  = COALESCE($4, description),
    department_id = COALESCE($5, department_id),
    weekly_hours = COALESCE($6, weekly_hours),
    is_active    = COALESCE($7, is_active),
    updated_at   = NOW()
WHERE id = $8 RETURNING id, code, name, credits, description, department_id, weekly_hours, is_active, created_at, updated_at
`

type UpdateSubjectParams struct {
	Code         pgtype.Text `json:"code"`
	Name         pgtype.Text `json:"name"`
	Credits      pgtype.Int4 `json:"credits"`
	Description  pgtype.Text `json:"description"`
	DepartmentID pgtype.Text `json:"department_id"`
	WeeklyHours  pgtype.Int4 `json:"weekly_hours"`
	IsActive     pgtype.Bool `json:"is_active"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (SubjectSubject, error) {
	row := q.db.QueryRow(ctx, updateSubject,
		arg.Code, arg.Name, arg.Credits, arg.Description,
		arg.DepartmentID, arg.WeeklyHours, arg.IsActive, arg.ID,
	)
	var i SubjectSubject
	err := row.Scan(
		&i.ID, &i.Code, &i.Name, &i.Credits, &i.Description,
		&i.DepartmentID, &i.WeeklyHours, &i.IsActive, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const deleteSubject = `-- name: DeleteSubject :exec
DELETE FROM subject.subjects WHERE id = $1
`

func (q *Queries) DeleteSubject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubject, id)
	return err
}

const listAllSubjectIDs = `-- name: ListAllSubjectIDs :many
SELECT id FROM subject.subjects ORDER BY id
`

func (q *Queries) ListAllSubjectIDs(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAllSubjectIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	return items, rows.Err()
}
