import { createRouter } from '@tanstack/react-router'
import { routeTree } from '../routeTree.gen'
import { queryClient } from './query-client'

// TanStack Router instance — routeTree.gen is auto-generated by the Vite plugin
export const router = createRouter({
  routeTree,
  context: {
    queryClient,
  },
  defaultPreload: 'intent',
  defaultPreloadStaleTime: 0,
  scrollRestoration: true,
})

// Register router for type safety across the app
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}
