// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enrollments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendEnrollmentEvent = `-- name: AppendEnrollmentEvent :exec
INSERT INTO student.event_store (aggregate_id, aggregate_type, event_type, payload)
VALUES ($1, 'enrollment_request', $2, $3)
`

type AppendEnrollmentEventParams struct {
	AggregateID pgtype.UUID `json:"aggregate_id"`
	EventType   string      `json:"event_type"`
	Payload     []byte      `json:"payload"`
}

func (q *Queries) AppendEnrollmentEvent(ctx context.Context, arg AppendEnrollmentEventParams) error {
	_, err := q.db.Exec(ctx, appendEnrollmentEvent, arg.AggregateID, arg.EventType, arg.Payload)
	return err
}

const countEnrollmentRequests = `-- name: CountEnrollmentRequests :one
SELECT COUNT(*)
FROM student.enrollment_requests
WHERE ($1::uuid IS NULL OR student_id = $1::uuid)
  AND ($2::uuid IS NULL OR semester_id = $2::uuid)
  AND ($3::text IS NULL OR status = $3::text)
`

type CountEnrollmentRequestsParams struct {
	StudentID  pgtype.UUID `json:"student_id"`
	SemesterID pgtype.UUID `json:"semester_id"`
	Status     pgtype.Text `json:"status"`
}

func (q *Queries) CountEnrollmentRequests(ctx context.Context, arg CountEnrollmentRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEnrollmentRequests, arg.StudentID, arg.SemesterID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEnrollmentRequest = `-- name: CreateEnrollmentRequest :one
INSERT INTO student.enrollment_requests (
    id,
    student_id,
    semester_id,
    offered_subject_id,
    subject_id,
    request_note
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, student_id, semester_id, offered_subject_id, subject_id, status, request_note, admin_note, requested_at, reviewed_at, reviewed_by
`

type CreateEnrollmentRequestParams struct {
	ID               pgtype.UUID `json:"id"`
	StudentID        pgtype.UUID `json:"student_id"`
	SemesterID       pgtype.UUID `json:"semester_id"`
	OfferedSubjectID pgtype.UUID `json:"offered_subject_id"`
	SubjectID        pgtype.UUID `json:"subject_id"`
	RequestNote      string      `json:"request_note"`
}

func (q *Queries) CreateEnrollmentRequest(ctx context.Context, arg CreateEnrollmentRequestParams) (StudentEnrollmentRequest, error) {
	row := q.db.QueryRow(ctx, createEnrollmentRequest,
		arg.ID,
		arg.StudentID,
		arg.SemesterID,
		arg.OfferedSubjectID,
		arg.SubjectID,
		arg.RequestNote,
	)
	var i StudentEnrollmentRequest
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.SemesterID,
		&i.OfferedSubjectID,
		&i.SubjectID,
		&i.Status,
		&i.RequestNote,
		&i.AdminNote,
		&i.RequestedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
	)
	return i, err
}

const getEnrollmentRequest = `-- name: GetEnrollmentRequest :one
SELECT id, student_id, semester_id, offered_subject_id, subject_id, status, request_note, admin_note, requested_at, reviewed_at, reviewed_by
FROM student.enrollment_requests
WHERE id = $1
`

func (q *Queries) GetEnrollmentRequest(ctx context.Context, id pgtype.UUID) (StudentEnrollmentRequest, error) {
	row := q.db.QueryRow(ctx, getEnrollmentRequest, id)
	var i StudentEnrollmentRequest
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.SemesterID,
		&i.OfferedSubjectID,
		&i.SubjectID,
		&i.Status,
		&i.RequestNote,
		&i.AdminNote,
		&i.RequestedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
	)
	return i, err
}

const getStudentEnrollments = `-- name: GetStudentEnrollments :many
SELECT id, student_id, semester_id, offered_subject_id, subject_id, status, request_note, admin_note, requested_at, reviewed_at, reviewed_by
FROM student.enrollment_requests
WHERE student_id = $1
  AND ($2::uuid IS NULL OR semester_id = $2::uuid)
ORDER BY requested_at DESC
`

type GetStudentEnrollmentsParams struct {
	StudentID  pgtype.UUID `json:"student_id"`
	SemesterID pgtype.UUID `json:"semester_id"`
}

func (q *Queries) GetStudentEnrollments(ctx context.Context, arg GetStudentEnrollmentsParams) ([]StudentEnrollmentRequest, error) {
	rows, err := q.db.Query(ctx, getStudentEnrollments, arg.StudentID, arg.SemesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudentEnrollmentRequest
	for rows.Next() {
		var i StudentEnrollmentRequest
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.SemesterID,
			&i.OfferedSubjectID,
			&i.SubjectID,
			&i.Status,
			&i.RequestNote,
			&i.AdminNote,
			&i.RequestedAt,
			&i.ReviewedAt,
			&i.ReviewedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnrollmentRequests = `-- name: ListEnrollmentRequests :many
SELECT id, student_id, semester_id, offered_subject_id, subject_id, status, request_note, admin_note, requested_at, reviewed_at, reviewed_by
FROM student.enrollment_requests
WHERE ($1::uuid IS NULL OR student_id = $1::uuid)
  AND ($2::uuid IS NULL OR semester_id = $2::uuid)
  AND ($3::text IS NULL OR status = $3::text)
ORDER BY requested_at DESC
LIMIT $5 OFFSET $4
`

type ListEnrollmentRequestsParams struct {
	StudentID   pgtype.UUID `json:"student_id"`
	SemesterID  pgtype.UUID `json:"semester_id"`
	Status      pgtype.Text `json:"status"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

func (q *Queries) ListEnrollmentRequests(ctx context.Context, arg ListEnrollmentRequestsParams) ([]StudentEnrollmentRequest, error) {
	rows, err := q.db.Query(ctx, listEnrollmentRequests,
		arg.StudentID,
		arg.SemesterID,
		arg.Status,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudentEnrollmentRequest
	for rows.Next() {
		var i StudentEnrollmentRequest
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.SemesterID,
			&i.OfferedSubjectID,
			&i.SubjectID,
			&i.Status,
			&i.RequestNote,
			&i.AdminNote,
			&i.RequestedAt,
			&i.ReviewedAt,
			&i.ReviewedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPassedEnrollmentSubjectIDs = `-- name: ListPassedEnrollmentSubjectIDs :many
SELECT subject_id
FROM student.enrollment_requests
WHERE student_id = $1
  AND status = 'completed'
ORDER BY requested_at DESC
`

func (q *Queries) ListPassedEnrollmentSubjectIDs(ctx context.Context, studentID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listPassedEnrollmentSubjectIDs, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var subject_id pgtype.UUID
		if err := rows.Scan(&subject_id); err != nil {
			return nil, err
		}
		items = append(items, subject_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewEnrollmentRequest = `-- name: ReviewEnrollmentRequest :one
UPDATE student.enrollment_requests
SET status = $1,
    admin_note = $2,
    reviewed_by = $3,
    reviewed_at = NOW()
WHERE id = $4
  AND status = 'pending'
RETURNING id, student_id, semester_id, offered_subject_id, subject_id, status, request_note, admin_note, requested_at, reviewed_at, reviewed_by
`

type ReviewEnrollmentRequestParams struct {
	Status     string      `json:"status"`
	AdminNote  string      `json:"admin_note"`
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) ReviewEnrollmentRequest(ctx context.Context, arg ReviewEnrollmentRequestParams) (StudentEnrollmentRequest, error) {
	row := q.db.QueryRow(ctx, reviewEnrollmentRequest,
		arg.Status,
		arg.AdminNote,
		arg.ReviewedBy,
		arg.ID,
	)
	var i StudentEnrollmentRequest
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.SemesterID,
		&i.OfferedSubjectID,
		&i.SubjectID,
		&i.Status,
		&i.RequestNote,
		&i.AdminNote,
		&i.RequestedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
	)
	return i, err
}
