// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type StudentEnrollmentRequest struct {
	ID               pgtype.UUID        `json:"id"`
	StudentID        pgtype.UUID        `json:"student_id"`
	SemesterID       pgtype.UUID        `json:"semester_id"`
	OfferedSubjectID pgtype.UUID        `json:"offered_subject_id"`
	SubjectID        pgtype.UUID        `json:"subject_id"`
	Status           string             `json:"status"`
	RequestNote      string             `json:"request_note"`
	AdminNote        string             `json:"admin_note"`
	RequestedAt      pgtype.Timestamptz `json:"requested_at"`
	ReviewedAt       pgtype.Timestamptz `json:"reviewed_at"`
	ReviewedBy       pgtype.UUID        `json:"reviewed_by"`
}

type StudentEventStore struct {
	ID            int64              `json:"id"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	AggregateType string             `json:"aggregate_type"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	Version       int64              `json:"version"`
	Timestamp     pgtype.Timestamptz `json:"timestamp"`
}

type StudentGrade struct {
	ID           pgtype.UUID        `json:"id"`
	EnrollmentID pgtype.UUID        `json:"enrollment_id"`
	GradeNumeric pgtype.Numeric     `json:"grade_numeric"`
	GradeLetter  pgtype.Text        `json:"grade_letter"`
	GradedBy     pgtype.UUID        `json:"graded_by"`
	GradedAt     pgtype.Timestamptz `json:"graded_at"`
	Notes        string             `json:"notes"`
}

type StudentStudent struct {
	ID             pgtype.UUID        `json:"id"`
	StudentCode    string             `json:"student_code"`
	UserID         pgtype.UUID        `json:"user_id"`
	FullName       string             `json:"full_name"`
	Email          string             `json:"email"`
	DepartmentID   pgtype.UUID        `json:"department_id"`
	EnrollmentYear int32              `json:"enrollment_year"`
	Status         string             `json:"status"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
