// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AppendEnrollmentEvent(ctx context.Context, arg AppendEnrollmentEventParams) error
	AssignGrade(ctx context.Context, arg AssignGradeParams) (AssignGradeRow, error)
	CountEnrollmentRequests(ctx context.Context, arg CountEnrollmentRequestsParams) (int64, error)
	CountStudents(ctx context.Context, arg CountStudentsParams) (int64, error)
	CreateEnrollmentRequest(ctx context.Context, arg CreateEnrollmentRequestParams) (StudentEnrollmentRequest, error)
	CreateStudent(ctx context.Context, arg CreateStudentParams) (StudentStudent, error)
	DeleteStudent(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	GetEnrollmentRequest(ctx context.Context, id pgtype.UUID) (StudentEnrollmentRequest, error)
	GetGrade(ctx context.Context, id pgtype.UUID) (GetGradeRow, error)
	GetStudentByID(ctx context.Context, id pgtype.UUID) (StudentStudent, error)
	GetStudentByUserID(ctx context.Context, userID pgtype.UUID) (StudentStudent, error)
	GetStudentEnrollments(ctx context.Context, arg GetStudentEnrollmentsParams) ([]StudentEnrollmentRequest, error)
	GetStudentTranscript(ctx context.Context, studentID pgtype.UUID) ([]GetStudentTranscriptRow, error)
	LinkUserToStudent(ctx context.Context, arg LinkUserToStudentParams) (StudentStudent, error)
	ListEnrollmentRequests(ctx context.Context, arg ListEnrollmentRequestsParams) ([]StudentEnrollmentRequest, error)
	ListPassedEnrollmentSubjectIDs(ctx context.Context, studentID pgtype.UUID) ([]pgtype.UUID, error)
	ListStudents(ctx context.Context, arg ListStudentsParams) ([]StudentStudent, error)
	MarkEnrollmentCompleted(ctx context.Context, enrollmentID pgtype.UUID) error
	ReviewEnrollmentRequest(ctx context.Context, arg ReviewEnrollmentRequestParams) (StudentEnrollmentRequest, error)
	UpdateGrade(ctx context.Context, arg UpdateGradeParams) (UpdateGradeRow, error)
	UpdateStudent(ctx context.Context, arg UpdateStudentParams) (StudentStudent, error)
}

var _ Querier = (*Queries)(nil)
