// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: students.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countStudents = `-- name: CountStudents :one
SELECT COUNT(*)
FROM student.students
WHERE is_active = true
  AND ($1::uuid IS NULL OR department_id = $1::uuid)
  AND ($2::text IS NULL OR status = $2::text)
`

type CountStudentsParams struct {
	DepartmentID pgtype.UUID `json:"department_id"`
	Status       pgtype.Text `json:"status"`
}

func (q *Queries) CountStudents(ctx context.Context, arg CountStudentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStudents, arg.DepartmentID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStudent = `-- name: CreateStudent :one
INSERT INTO student.students (
    student_code,
    user_id,
    full_name,
    email,
    department_id,
    enrollment_year,
    status,
    is_active
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, student_code, user_id, full_name, email, department_id, enrollment_year, status, is_active, created_at, updated_at
`

type CreateStudentParams struct {
	StudentCode    string      `json:"student_code"`
	UserID         pgtype.UUID `json:"user_id"`
	FullName       string      `json:"full_name"`
	Email          string      `json:"email"`
	DepartmentID   pgtype.UUID `json:"department_id"`
	EnrollmentYear int32       `json:"enrollment_year"`
	Status         string      `json:"status"`
	IsActive       bool        `json:"is_active"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (StudentStudent, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.StudentCode,
		arg.UserID,
		arg.FullName,
		arg.Email,
		arg.DepartmentID,
		arg.EnrollmentYear,
		arg.Status,
		arg.IsActive,
	)
	var i StudentStudent
	err := row.Scan(
		&i.ID,
		&i.StudentCode,
		&i.UserID,
		&i.FullName,
		&i.Email,
		&i.DepartmentID,
		&i.EnrollmentYear,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStudent = `-- name: DeleteStudent :one
UPDATE student.students
SET is_active = false,
    updated_at = NOW()
WHERE id = $1 AND is_active = true
RETURNING id
`

func (q *Queries) DeleteStudent(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteStudent, id)
	err := row.Scan(&id)
	return id, err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT id, student_code, user_id, full_name, email, department_id, enrollment_year, status, is_active, created_at, updated_at FROM student.students WHERE id = $1 AND is_active = true
`

func (q *Queries) GetStudentByID(ctx context.Context, id pgtype.UUID) (StudentStudent, error) {
	row := q.db.QueryRow(ctx, getStudentByID, id)
	var i StudentStudent
	err := row.Scan(
		&i.ID,
		&i.StudentCode,
		&i.UserID,
		&i.FullName,
		&i.Email,
		&i.DepartmentID,
		&i.EnrollmentYear,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStudents = `-- name: ListStudents :many
SELECT id, student_code, user_id, full_name, email, department_id, enrollment_year, status, is_active, created_at, updated_at
FROM student.students
WHERE is_active = true
  AND ($1::uuid IS NULL OR department_id = $1::uuid)
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY full_name
LIMIT $4 OFFSET $3
`

type ListStudentsParams struct {
	DepartmentID pgtype.UUID `json:"department_id"`
	Status       pgtype.Text `json:"status"`
	OffsetCount  int32       `json:"offset_count"`
	LimitCount   int32       `json:"limit_count"`
}

func (q *Queries) ListStudents(ctx context.Context, arg ListStudentsParams) ([]StudentStudent, error) {
	rows, err := q.db.Query(ctx, listStudents,
		arg.DepartmentID,
		arg.Status,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudentStudent
	for rows.Next() {
		var i StudentStudent
		if err := rows.Scan(
			&i.ID,
			&i.StudentCode,
			&i.UserID,
			&i.FullName,
			&i.Email,
			&i.DepartmentID,
			&i.EnrollmentYear,
			&i.Status,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudent = `-- name: UpdateStudent :one
UPDATE student.students
SET user_id = $2,
    full_name = $3,
    email = $4,
    department_id = $5,
    enrollment_year = $6,
    status = $7,
    is_active = $8,
    updated_at = NOW()
WHERE id = $1 AND is_active = true
RETURNING id, student_code, user_id, full_name, email, department_id, enrollment_year, status, is_active, created_at, updated_at
`

type UpdateStudentParams struct {
	ID             pgtype.UUID `json:"id"`
	UserID         pgtype.UUID `json:"user_id"`
	FullName       string      `json:"full_name"`
	Email          string      `json:"email"`
	DepartmentID   pgtype.UUID `json:"department_id"`
	EnrollmentYear int32       `json:"enrollment_year"`
	Status         string      `json:"status"`
	IsActive       bool        `json:"is_active"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (StudentStudent, error) {
	row := q.db.QueryRow(ctx, updateStudent,
		arg.ID,
		arg.UserID,
		arg.FullName,
		arg.Email,
		arg.DepartmentID,
		arg.EnrollmentYear,
		arg.Status,
		arg.IsActive,
	)
	var i StudentStudent
	err := row.Scan(
		&i.ID,
		&i.StudentCode,
		&i.UserID,
		&i.FullName,
		&i.Email,
		&i.DepartmentID,
		&i.EnrollmentYear,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
