// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transcript.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignGrade = `-- name: AssignGrade :one
INSERT INTO student.grades (
    id,
    enrollment_id,
    grade_numeric,
    graded_by,
    notes
) VALUES (
    $1,
    $2,
    $3::double precision,
    $4,
    $5
)
RETURNING
    id,
    enrollment_id,
    grade_numeric::double precision AS grade_numeric,
    grade_letter,
    graded_by,
    graded_at,
    notes
`

type AssignGradeParams struct {
	ID           pgtype.UUID `json:"id"`
	EnrollmentID pgtype.UUID `json:"enrollment_id"`
	GradeNumeric float64     `json:"grade_numeric"`
	GradedBy     pgtype.UUID `json:"graded_by"`
	Notes        string      `json:"notes"`
}

type AssignGradeRow struct {
	ID           pgtype.UUID        `json:"id"`
	EnrollmentID pgtype.UUID        `json:"enrollment_id"`
	GradeNumeric float64            `json:"grade_numeric"`
	GradeLetter  pgtype.Text        `json:"grade_letter"`
	GradedBy     pgtype.UUID        `json:"graded_by"`
	GradedAt     pgtype.Timestamptz `json:"graded_at"`
	Notes        string             `json:"notes"`
}

func (q *Queries) AssignGrade(ctx context.Context, arg AssignGradeParams) (AssignGradeRow, error) {
	row := q.db.QueryRow(ctx, assignGrade,
		arg.ID,
		arg.EnrollmentID,
		arg.GradeNumeric,
		arg.GradedBy,
		arg.Notes,
	)
	var i AssignGradeRow
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.GradeNumeric,
		&i.GradeLetter,
		&i.GradedBy,
		&i.GradedAt,
		&i.Notes,
	)
	return i, err
}

const getGrade = `-- name: GetGrade :one
SELECT
    id,
    enrollment_id,
    grade_numeric::double precision AS grade_numeric,
    grade_letter,
    graded_by,
    graded_at,
    notes
FROM student.grades
WHERE id = $1
`

type GetGradeRow struct {
	ID           pgtype.UUID        `json:"id"`
	EnrollmentID pgtype.UUID        `json:"enrollment_id"`
	GradeNumeric float64            `json:"grade_numeric"`
	GradeLetter  pgtype.Text        `json:"grade_letter"`
	GradedBy     pgtype.UUID        `json:"graded_by"`
	GradedAt     pgtype.Timestamptz `json:"graded_at"`
	Notes        string             `json:"notes"`
}

func (q *Queries) GetGrade(ctx context.Context, id pgtype.UUID) (GetGradeRow, error) {
	row := q.db.QueryRow(ctx, getGrade, id)
	var i GetGradeRow
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.GradeNumeric,
		&i.GradeLetter,
		&i.GradedBy,
		&i.GradedAt,
		&i.Notes,
	)
	return i, err
}

const getStudentTranscript = `-- name: GetStudentTranscript :many
SELECT
    er.id AS enrollment_id,
    er.student_id,
    er.semester_id,
    er.subject_id,
    er.offered_subject_id,
    er.status,
    er.requested_at,
    COALESCE(g.grade_numeric::double precision, 0::double precision) AS grade_numeric,
    g.grade_letter,
    g.graded_at
FROM student.enrollment_requests er
LEFT JOIN student.grades g ON g.enrollment_id = er.id
WHERE er.student_id = $1
  AND er.status IN ('approved', 'completed')
ORDER BY er.requested_at DESC
`

type GetStudentTranscriptRow struct {
	EnrollmentID     pgtype.UUID        `json:"enrollment_id"`
	StudentID        pgtype.UUID        `json:"student_id"`
	SemesterID       pgtype.UUID        `json:"semester_id"`
	SubjectID        pgtype.UUID        `json:"subject_id"`
	OfferedSubjectID pgtype.UUID        `json:"offered_subject_id"`
	Status           string             `json:"status"`
	RequestedAt      pgtype.Timestamptz `json:"requested_at"`
	GradeNumeric     interface{}        `json:"grade_numeric"`
	GradeLetter      pgtype.Text        `json:"grade_letter"`
	GradedAt         pgtype.Timestamptz `json:"graded_at"`
}

func (q *Queries) GetStudentTranscript(ctx context.Context, studentID pgtype.UUID) ([]GetStudentTranscriptRow, error) {
	rows, err := q.db.Query(ctx, getStudentTranscript, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentTranscriptRow
	for rows.Next() {
		var i GetStudentTranscriptRow
		if err := rows.Scan(
			&i.EnrollmentID,
			&i.StudentID,
			&i.SemesterID,
			&i.SubjectID,
			&i.OfferedSubjectID,
			&i.Status,
			&i.RequestedAt,
			&i.GradeNumeric,
			&i.GradeLetter,
			&i.GradedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEnrollmentCompleted = `-- name: MarkEnrollmentCompleted :exec
UPDATE student.enrollment_requests
SET status = 'completed'
WHERE id = $1
`

func (q *Queries) MarkEnrollmentCompleted(ctx context.Context, enrollmentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEnrollmentCompleted, enrollmentID)
	return err
}

const updateGrade = `-- name: UpdateGrade :one
UPDATE student.grades
SET grade_numeric = $1::double precision,
    graded_by = $2,
    notes = $3,
    graded_at = NOW()
WHERE id = $4
RETURNING
    id,
    enrollment_id,
    grade_numeric::double precision AS grade_numeric,
    grade_letter,
    graded_by,
    graded_at,
    notes
`

type UpdateGradeParams struct {
	GradeNumeric float64     `json:"grade_numeric"`
	GradedBy     pgtype.UUID `json:"graded_by"`
	Notes        string      `json:"notes"`
	ID           pgtype.UUID `json:"id"`
}

type UpdateGradeRow struct {
	ID           pgtype.UUID        `json:"id"`
	EnrollmentID pgtype.UUID        `json:"enrollment_id"`
	GradeNumeric float64            `json:"grade_numeric"`
	GradeLetter  pgtype.Text        `json:"grade_letter"`
	GradedBy     pgtype.UUID        `json:"graded_by"`
	GradedAt     pgtype.Timestamptz `json:"graded_at"`
	Notes        string             `json:"notes"`
}

func (q *Queries) UpdateGrade(ctx context.Context, arg UpdateGradeParams) (UpdateGradeRow, error) {
	row := q.db.QueryRow(ctx, updateGrade,
		arg.GradeNumeric,
		arg.GradedBy,
		arg.Notes,
		arg.ID,
	)
	var i UpdateGradeRow
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.GradeNumeric,
		&i.GradeLetter,
		&i.GradedBy,
		&i.GradedAt,
		&i.Notes,
	)
	return i, err
}
