/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnalyticsRouteRouteImport } from './routes/_authenticated/analytics/route'
import { Route as AuthenticatedTimetableIndexRouteImport } from './routes/_authenticated/timetable/index'
import { Route as AuthenticatedSubjectsIndexRouteImport } from './routes/_authenticated/subjects/index'
import { Route as AuthenticatedHrIndexRouteImport } from './routes/_authenticated/hr/index'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics/index'
import { Route as AuthenticatedSubjectsPrerequisitesRouteImport } from './routes/_authenticated/subjects/prerequisites'
import { Route as AuthenticatedSubjectsNewRouteImport } from './routes/_authenticated/subjects/new'
import { Route as AuthenticatedTimetableSemestersIndexRouteImport } from './routes/_authenticated/timetable/semesters/index'
import { Route as AuthenticatedTimetableSchedulesIndexRouteImport } from './routes/_authenticated/timetable/schedules/index'
import { Route as AuthenticatedTimetableGenerateIndexRouteImport } from './routes/_authenticated/timetable/generate/index'
import { Route as AuthenticatedTimetableAssignIndexRouteImport } from './routes/_authenticated/timetable/assign/index'
import { Route as AuthenticatedSubjectsOfferingsIndexRouteImport } from './routes/_authenticated/subjects/offerings/index'
import { Route as AuthenticatedSubjectsIdIndexRouteImport } from './routes/_authenticated/subjects/$id/index'
import { Route as AuthenticatedHrTeachersIndexRouteImport } from './routes/_authenticated/hr/teachers/index'
import { Route as AuthenticatedHrDepartmentsIndexRouteImport } from './routes/_authenticated/hr/departments/index'
import { Route as AuthenticatedTimetableSemestersNewRouteImport } from './routes/_authenticated/timetable/semesters/new'
import { Route as AuthenticatedTimetableSemestersIdRouteImport } from './routes/_authenticated/timetable/semesters/$id'
import { Route as AuthenticatedSubjectsIdEditRouteImport } from './routes/_authenticated/subjects/$id/edit'
import { Route as AuthenticatedHrTeachersNewRouteImport } from './routes/_authenticated/hr/teachers/new'
import { Route as AuthenticatedHrDepartmentsNewRouteImport } from './routes/_authenticated/hr/departments/new'
import { Route as AuthenticatedTimetableSchedulesIdIndexRouteImport } from './routes/_authenticated/timetable/schedules/$id/index'
import { Route as AuthenticatedHrTeachersIdIndexRouteImport } from './routes/_authenticated/hr/teachers/$id/index'
import { Route as AuthenticatedHrTeachersIdEditRouteImport } from './routes/_authenticated/hr/teachers/$id/edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRouteRoute =
  AuthenticatedAnalyticsRouteRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimetableIndexRoute =
  AuthenticatedTimetableIndexRouteImport.update({
    id: '/timetable/',
    path: '/timetable/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectsIndexRoute =
  AuthenticatedSubjectsIndexRouteImport.update({
    id: '/subjects/',
    path: '/subjects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrIndexRoute = AuthenticatedHrIndexRouteImport.update({
  id: '/hr/',
  path: '/hr/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAnalyticsRouteRoute,
  } as any)
const AuthenticatedSubjectsPrerequisitesRoute =
  AuthenticatedSubjectsPrerequisitesRouteImport.update({
    id: '/subjects/prerequisites',
    path: '/subjects/prerequisites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectsNewRoute =
  AuthenticatedSubjectsNewRouteImport.update({
    id: '/subjects/new',
    path: '/subjects/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimetableSemestersIndexRoute =
  AuthenticatedTimetableSemestersIndexRouteImport.update({
    id: '/timetable/semesters/',
    path: '/timetable/semesters/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimetableSchedulesIndexRoute =
  AuthenticatedTimetableSchedulesIndexRouteImport.update({
    id: '/timetable/schedules/',
    path: '/timetable/schedules/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimetableGenerateIndexRoute =
  AuthenticatedTimetableGenerateIndexRouteImport.update({
    id: '/timetable/generate/',
    path: '/timetable/generate/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimetableAssignIndexRoute =
  AuthenticatedTimetableAssignIndexRouteImport.update({
    id: '/timetable/assign/',
    path: '/timetable/assign/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectsOfferingsIndexRoute =
  AuthenticatedSubjectsOfferingsIndexRouteImport.update({
    id: '/subjects/offerings/',
    path: '/subjects/offerings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectsIdIndexRoute =
  AuthenticatedSubjectsIdIndexRouteImport.update({
    id: '/subjects/$id/',
    path: '/subjects/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrTeachersIndexRoute =
  AuthenticatedHrTeachersIndexRouteImport.update({
    id: '/hr/teachers/',
    path: '/hr/teachers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrDepartmentsIndexRoute =
  AuthenticatedHrDepartmentsIndexRouteImport.update({
    id: '/hr/departments/',
    path: '/hr/departments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimetableSemestersNewRoute =
  AuthenticatedTimetableSemestersNewRouteImport.update({
    id: '/timetable/semesters/new',
    path: '/timetable/semesters/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimetableSemestersIdRoute =
  AuthenticatedTimetableSemestersIdRouteImport.update({
    id: '/timetable/semesters/$id',
    path: '/timetable/semesters/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectsIdEditRoute =
  AuthenticatedSubjectsIdEditRouteImport.update({
    id: '/subjects/$id/edit',
    path: '/subjects/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrTeachersNewRoute =
  AuthenticatedHrTeachersNewRouteImport.update({
    id: '/hr/teachers/new',
    path: '/hr/teachers/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrDepartmentsNewRoute =
  AuthenticatedHrDepartmentsNewRouteImport.update({
    id: '/hr/departments/new',
    path: '/hr/departments/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimetableSchedulesIdIndexRoute =
  AuthenticatedTimetableSchedulesIdIndexRouteImport.update({
    id: '/timetable/schedules/$id/',
    path: '/timetable/schedules/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrTeachersIdIndexRoute =
  AuthenticatedHrTeachersIdIndexRouteImport.update({
    id: '/hr/teachers/$id/',
    path: '/hr/teachers/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrTeachersIdEditRoute =
  AuthenticatedHrTeachersIdEditRouteImport.update({
    id: '/hr/teachers/$id/edit',
    path: '/hr/teachers/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analytics': typeof AuthenticatedAnalyticsRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/subjects/new': typeof AuthenticatedSubjectsNewRoute
  '/subjects/prerequisites': typeof AuthenticatedSubjectsPrerequisitesRoute
  '/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/hr/': typeof AuthenticatedHrIndexRoute
  '/subjects/': typeof AuthenticatedSubjectsIndexRoute
  '/timetable/': typeof AuthenticatedTimetableIndexRoute
  '/hr/departments/new': typeof AuthenticatedHrDepartmentsNewRoute
  '/hr/teachers/new': typeof AuthenticatedHrTeachersNewRoute
  '/subjects/$id/edit': typeof AuthenticatedSubjectsIdEditRoute
  '/timetable/semesters/$id': typeof AuthenticatedTimetableSemestersIdRoute
  '/timetable/semesters/new': typeof AuthenticatedTimetableSemestersNewRoute
  '/hr/departments/': typeof AuthenticatedHrDepartmentsIndexRoute
  '/hr/teachers/': typeof AuthenticatedHrTeachersIndexRoute
  '/subjects/$id/': typeof AuthenticatedSubjectsIdIndexRoute
  '/subjects/offerings/': typeof AuthenticatedSubjectsOfferingsIndexRoute
  '/timetable/assign/': typeof AuthenticatedTimetableAssignIndexRoute
  '/timetable/generate/': typeof AuthenticatedTimetableGenerateIndexRoute
  '/timetable/schedules/': typeof AuthenticatedTimetableSchedulesIndexRoute
  '/timetable/semesters/': typeof AuthenticatedTimetableSemestersIndexRoute
  '/hr/teachers/$id/edit': typeof AuthenticatedHrTeachersIdEditRoute
  '/hr/teachers/$id/': typeof AuthenticatedHrTeachersIdIndexRoute
  '/timetable/schedules/$id/': typeof AuthenticatedTimetableSchedulesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/subjects/new': typeof AuthenticatedSubjectsNewRoute
  '/subjects/prerequisites': typeof AuthenticatedSubjectsPrerequisitesRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/hr': typeof AuthenticatedHrIndexRoute
  '/subjects': typeof AuthenticatedSubjectsIndexRoute
  '/timetable': typeof AuthenticatedTimetableIndexRoute
  '/hr/departments/new': typeof AuthenticatedHrDepartmentsNewRoute
  '/hr/teachers/new': typeof AuthenticatedHrTeachersNewRoute
  '/subjects/$id/edit': typeof AuthenticatedSubjectsIdEditRoute
  '/timetable/semesters/$id': typeof AuthenticatedTimetableSemestersIdRoute
  '/timetable/semesters/new': typeof AuthenticatedTimetableSemestersNewRoute
  '/hr/departments': typeof AuthenticatedHrDepartmentsIndexRoute
  '/hr/teachers': typeof AuthenticatedHrTeachersIndexRoute
  '/subjects/$id': typeof AuthenticatedSubjectsIdIndexRoute
  '/subjects/offerings': typeof AuthenticatedSubjectsOfferingsIndexRoute
  '/timetable/assign': typeof AuthenticatedTimetableAssignIndexRoute
  '/timetable/generate': typeof AuthenticatedTimetableGenerateIndexRoute
  '/timetable/schedules': typeof AuthenticatedTimetableSchedulesIndexRoute
  '/timetable/semesters': typeof AuthenticatedTimetableSemestersIndexRoute
  '/hr/teachers/$id/edit': typeof AuthenticatedHrTeachersIdEditRoute
  '/hr/teachers/$id': typeof AuthenticatedHrTeachersIdIndexRoute
  '/timetable/schedules/$id': typeof AuthenticatedTimetableSchedulesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/subjects/new': typeof AuthenticatedSubjectsNewRoute
  '/_authenticated/subjects/prerequisites': typeof AuthenticatedSubjectsPrerequisitesRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/hr/': typeof AuthenticatedHrIndexRoute
  '/_authenticated/subjects/': typeof AuthenticatedSubjectsIndexRoute
  '/_authenticated/timetable/': typeof AuthenticatedTimetableIndexRoute
  '/_authenticated/hr/departments/new': typeof AuthenticatedHrDepartmentsNewRoute
  '/_authenticated/hr/teachers/new': typeof AuthenticatedHrTeachersNewRoute
  '/_authenticated/subjects/$id/edit': typeof AuthenticatedSubjectsIdEditRoute
  '/_authenticated/timetable/semesters/$id': typeof AuthenticatedTimetableSemestersIdRoute
  '/_authenticated/timetable/semesters/new': typeof AuthenticatedTimetableSemestersNewRoute
  '/_authenticated/hr/departments/': typeof AuthenticatedHrDepartmentsIndexRoute
  '/_authenticated/hr/teachers/': typeof AuthenticatedHrTeachersIndexRoute
  '/_authenticated/subjects/$id/': typeof AuthenticatedSubjectsIdIndexRoute
  '/_authenticated/subjects/offerings/': typeof AuthenticatedSubjectsOfferingsIndexRoute
  '/_authenticated/timetable/assign/': typeof AuthenticatedTimetableAssignIndexRoute
  '/_authenticated/timetable/generate/': typeof AuthenticatedTimetableGenerateIndexRoute
  '/_authenticated/timetable/schedules/': typeof AuthenticatedTimetableSchedulesIndexRoute
  '/_authenticated/timetable/semesters/': typeof AuthenticatedTimetableSemestersIndexRoute
  '/_authenticated/hr/teachers/$id/edit': typeof AuthenticatedHrTeachersIdEditRoute
  '/_authenticated/hr/teachers/$id/': typeof AuthenticatedHrTeachersIdIndexRoute
  '/_authenticated/timetable/schedules/$id/': typeof AuthenticatedTimetableSchedulesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/analytics'
    | '/dashboard'
    | '/subjects/new'
    | '/subjects/prerequisites'
    | '/analytics/'
    | '/hr/'
    | '/subjects/'
    | '/timetable/'
    | '/hr/departments/new'
    | '/hr/teachers/new'
    | '/subjects/$id/edit'
    | '/timetable/semesters/$id'
    | '/timetable/semesters/new'
    | '/hr/departments/'
    | '/hr/teachers/'
    | '/subjects/$id/'
    | '/subjects/offerings/'
    | '/timetable/assign/'
    | '/timetable/generate/'
    | '/timetable/schedules/'
    | '/timetable/semesters/'
    | '/hr/teachers/$id/edit'
    | '/hr/teachers/$id/'
    | '/timetable/schedules/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/subjects/new'
    | '/subjects/prerequisites'
    | '/analytics'
    | '/hr'
    | '/subjects'
    | '/timetable'
    | '/hr/departments/new'
    | '/hr/teachers/new'
    | '/subjects/$id/edit'
    | '/timetable/semesters/$id'
    | '/timetable/semesters/new'
    | '/hr/departments'
    | '/hr/teachers'
    | '/subjects/$id'
    | '/subjects/offerings'
    | '/timetable/assign'
    | '/timetable/generate'
    | '/timetable/schedules'
    | '/timetable/semesters'
    | '/hr/teachers/$id/edit'
    | '/hr/teachers/$id'
    | '/timetable/schedules/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/subjects/new'
    | '/_authenticated/subjects/prerequisites'
    | '/_authenticated/analytics/'
    | '/_authenticated/hr/'
    | '/_authenticated/subjects/'
    | '/_authenticated/timetable/'
    | '/_authenticated/hr/departments/new'
    | '/_authenticated/hr/teachers/new'
    | '/_authenticated/subjects/$id/edit'
    | '/_authenticated/timetable/semesters/$id'
    | '/_authenticated/timetable/semesters/new'
    | '/_authenticated/hr/departments/'
    | '/_authenticated/hr/teachers/'
    | '/_authenticated/subjects/$id/'
    | '/_authenticated/subjects/offerings/'
    | '/_authenticated/timetable/assign/'
    | '/_authenticated/timetable/generate/'
    | '/_authenticated/timetable/schedules/'
    | '/_authenticated/timetable/semesters/'
    | '/_authenticated/hr/teachers/$id/edit'
    | '/_authenticated/hr/teachers/$id/'
    | '/_authenticated/timetable/schedules/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable/': {
      id: '/_authenticated/timetable/'
      path: '/timetable'
      fullPath: '/timetable/'
      preLoaderRoute: typeof AuthenticatedTimetableIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects/': {
      id: '/_authenticated/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof AuthenticatedSubjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/': {
      id: '/_authenticated/hr/'
      path: '/hr'
      fullPath: '/hr/'
      preLoaderRoute: typeof AuthenticatedHrIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRouteRoute
    }
    '/_authenticated/subjects/prerequisites': {
      id: '/_authenticated/subjects/prerequisites'
      path: '/subjects/prerequisites'
      fullPath: '/subjects/prerequisites'
      preLoaderRoute: typeof AuthenticatedSubjectsPrerequisitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects/new': {
      id: '/_authenticated/subjects/new'
      path: '/subjects/new'
      fullPath: '/subjects/new'
      preLoaderRoute: typeof AuthenticatedSubjectsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable/semesters/': {
      id: '/_authenticated/timetable/semesters/'
      path: '/timetable/semesters'
      fullPath: '/timetable/semesters/'
      preLoaderRoute: typeof AuthenticatedTimetableSemestersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable/schedules/': {
      id: '/_authenticated/timetable/schedules/'
      path: '/timetable/schedules'
      fullPath: '/timetable/schedules/'
      preLoaderRoute: typeof AuthenticatedTimetableSchedulesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable/generate/': {
      id: '/_authenticated/timetable/generate/'
      path: '/timetable/generate'
      fullPath: '/timetable/generate/'
      preLoaderRoute: typeof AuthenticatedTimetableGenerateIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable/assign/': {
      id: '/_authenticated/timetable/assign/'
      path: '/timetable/assign'
      fullPath: '/timetable/assign/'
      preLoaderRoute: typeof AuthenticatedTimetableAssignIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects/offerings/': {
      id: '/_authenticated/subjects/offerings/'
      path: '/subjects/offerings'
      fullPath: '/subjects/offerings/'
      preLoaderRoute: typeof AuthenticatedSubjectsOfferingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects/$id/': {
      id: '/_authenticated/subjects/$id/'
      path: '/subjects/$id'
      fullPath: '/subjects/$id/'
      preLoaderRoute: typeof AuthenticatedSubjectsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/teachers/': {
      id: '/_authenticated/hr/teachers/'
      path: '/hr/teachers'
      fullPath: '/hr/teachers/'
      preLoaderRoute: typeof AuthenticatedHrTeachersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/departments/': {
      id: '/_authenticated/hr/departments/'
      path: '/hr/departments'
      fullPath: '/hr/departments/'
      preLoaderRoute: typeof AuthenticatedHrDepartmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable/semesters/new': {
      id: '/_authenticated/timetable/semesters/new'
      path: '/timetable/semesters/new'
      fullPath: '/timetable/semesters/new'
      preLoaderRoute: typeof AuthenticatedTimetableSemestersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable/semesters/$id': {
      id: '/_authenticated/timetable/semesters/$id'
      path: '/timetable/semesters/$id'
      fullPath: '/timetable/semesters/$id'
      preLoaderRoute: typeof AuthenticatedTimetableSemestersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects/$id/edit': {
      id: '/_authenticated/subjects/$id/edit'
      path: '/subjects/$id/edit'
      fullPath: '/subjects/$id/edit'
      preLoaderRoute: typeof AuthenticatedSubjectsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/teachers/new': {
      id: '/_authenticated/hr/teachers/new'
      path: '/hr/teachers/new'
      fullPath: '/hr/teachers/new'
      preLoaderRoute: typeof AuthenticatedHrTeachersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/departments/new': {
      id: '/_authenticated/hr/departments/new'
      path: '/hr/departments/new'
      fullPath: '/hr/departments/new'
      preLoaderRoute: typeof AuthenticatedHrDepartmentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable/schedules/$id/': {
      id: '/_authenticated/timetable/schedules/$id/'
      path: '/timetable/schedules/$id'
      fullPath: '/timetable/schedules/$id/'
      preLoaderRoute: typeof AuthenticatedTimetableSchedulesIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/teachers/$id/': {
      id: '/_authenticated/hr/teachers/$id/'
      path: '/hr/teachers/$id'
      fullPath: '/hr/teachers/$id/'
      preLoaderRoute: typeof AuthenticatedHrTeachersIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/teachers/$id/edit': {
      id: '/_authenticated/hr/teachers/$id/edit'
      path: '/hr/teachers/$id/edit'
      fullPath: '/hr/teachers/$id/edit'
      preLoaderRoute: typeof AuthenticatedHrTeachersIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAnalyticsRouteRouteChildren {
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
}

const AuthenticatedAnalyticsRouteRouteChildren: AuthenticatedAnalyticsRouteRouteChildren =
  {
    AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  }

const AuthenticatedAnalyticsRouteRouteWithChildren =
  AuthenticatedAnalyticsRouteRoute._addFileChildren(
    AuthenticatedAnalyticsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRouteRoute: typeof AuthenticatedAnalyticsRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSubjectsNewRoute: typeof AuthenticatedSubjectsNewRoute
  AuthenticatedSubjectsPrerequisitesRoute: typeof AuthenticatedSubjectsPrerequisitesRoute
  AuthenticatedHrIndexRoute: typeof AuthenticatedHrIndexRoute
  AuthenticatedSubjectsIndexRoute: typeof AuthenticatedSubjectsIndexRoute
  AuthenticatedTimetableIndexRoute: typeof AuthenticatedTimetableIndexRoute
  AuthenticatedHrDepartmentsNewRoute: typeof AuthenticatedHrDepartmentsNewRoute
  AuthenticatedHrTeachersNewRoute: typeof AuthenticatedHrTeachersNewRoute
  AuthenticatedSubjectsIdEditRoute: typeof AuthenticatedSubjectsIdEditRoute
  AuthenticatedTimetableSemestersIdRoute: typeof AuthenticatedTimetableSemestersIdRoute
  AuthenticatedTimetableSemestersNewRoute: typeof AuthenticatedTimetableSemestersNewRoute
  AuthenticatedHrDepartmentsIndexRoute: typeof AuthenticatedHrDepartmentsIndexRoute
  AuthenticatedHrTeachersIndexRoute: typeof AuthenticatedHrTeachersIndexRoute
  AuthenticatedSubjectsIdIndexRoute: typeof AuthenticatedSubjectsIdIndexRoute
  AuthenticatedSubjectsOfferingsIndexRoute: typeof AuthenticatedSubjectsOfferingsIndexRoute
  AuthenticatedTimetableAssignIndexRoute: typeof AuthenticatedTimetableAssignIndexRoute
  AuthenticatedTimetableGenerateIndexRoute: typeof AuthenticatedTimetableGenerateIndexRoute
  AuthenticatedTimetableSchedulesIndexRoute: typeof AuthenticatedTimetableSchedulesIndexRoute
  AuthenticatedTimetableSemestersIndexRoute: typeof AuthenticatedTimetableSemestersIndexRoute
  AuthenticatedHrTeachersIdEditRoute: typeof AuthenticatedHrTeachersIdEditRoute
  AuthenticatedHrTeachersIdIndexRoute: typeof AuthenticatedHrTeachersIdIndexRoute
  AuthenticatedTimetableSchedulesIdIndexRoute: typeof AuthenticatedTimetableSchedulesIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRouteRoute:
    AuthenticatedAnalyticsRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSubjectsNewRoute: AuthenticatedSubjectsNewRoute,
  AuthenticatedSubjectsPrerequisitesRoute:
    AuthenticatedSubjectsPrerequisitesRoute,
  AuthenticatedHrIndexRoute: AuthenticatedHrIndexRoute,
  AuthenticatedSubjectsIndexRoute: AuthenticatedSubjectsIndexRoute,
  AuthenticatedTimetableIndexRoute: AuthenticatedTimetableIndexRoute,
  AuthenticatedHrDepartmentsNewRoute: AuthenticatedHrDepartmentsNewRoute,
  AuthenticatedHrTeachersNewRoute: AuthenticatedHrTeachersNewRoute,
  AuthenticatedSubjectsIdEditRoute: AuthenticatedSubjectsIdEditRoute,
  AuthenticatedTimetableSemestersIdRoute:
    AuthenticatedTimetableSemestersIdRoute,
  AuthenticatedTimetableSemestersNewRoute:
    AuthenticatedTimetableSemestersNewRoute,
  AuthenticatedHrDepartmentsIndexRoute: AuthenticatedHrDepartmentsIndexRoute,
  AuthenticatedHrTeachersIndexRoute: AuthenticatedHrTeachersIndexRoute,
  AuthenticatedSubjectsIdIndexRoute: AuthenticatedSubjectsIdIndexRoute,
  AuthenticatedSubjectsOfferingsIndexRoute:
    AuthenticatedSubjectsOfferingsIndexRoute,
  AuthenticatedTimetableAssignIndexRoute:
    AuthenticatedTimetableAssignIndexRoute,
  AuthenticatedTimetableGenerateIndexRoute:
    AuthenticatedTimetableGenerateIndexRoute,
  AuthenticatedTimetableSchedulesIndexRoute:
    AuthenticatedTimetableSchedulesIndexRoute,
  AuthenticatedTimetableSemestersIndexRoute:
    AuthenticatedTimetableSemestersIndexRoute,
  AuthenticatedHrTeachersIdEditRoute: AuthenticatedHrTeachersIdEditRoute,
  AuthenticatedHrTeachersIdIndexRoute: AuthenticatedHrTeachersIdIndexRoute,
  AuthenticatedTimetableSchedulesIdIndexRoute:
    AuthenticatedTimetableSchedulesIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
