/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StudentRouteRouteImport } from './routes/_student/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnalyticsRouteRouteImport } from './routes/_authenticated/analytics/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedTimetableIndexRouteImport } from './routes/_authenticated/timetable/index'
import { Route as AuthenticatedSubjectsIndexRouteImport } from './routes/_authenticated/subjects/index'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedHrIndexRouteImport } from './routes/_authenticated/hr/index'
import { Route as AuthenticatedHelpIndexRouteImport } from './routes/_authenticated/help/index'
import { Route as AuthenticatedGradesIndexRouteImport } from './routes/_authenticated/grades/index'
import { Route as AuthenticatedEnrollmentsIndexRouteImport } from './routes/_authenticated/enrollments/index'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics/index'
import { Route as StudentStudentTranscriptRouteImport } from './routes/_student/student/transcript'
import { Route as StudentStudentSubjectsRouteImport } from './routes/_student/student/subjects'
import { Route as StudentStudentProfileRouteImport } from './routes/_student/student/profile'
import { Route as StudentStudentDashboardRouteImport } from './routes/_student/student/dashboard'
import { Route as AuthenticatedSubjectsPrerequisitesRouteImport } from './routes/_authenticated/subjects/prerequisites'
import { Route as AuthenticatedSubjectsNewRouteImport } from './routes/_authenticated/subjects/new'
import { Route as AuthenticatedTimetableSemestersIndexRouteImport } from './routes/_authenticated/timetable/semesters/index'
import { Route as AuthenticatedTimetableSchedulesIndexRouteImport } from './routes/_authenticated/timetable/schedules/index'
import { Route as AuthenticatedTimetableGenerateIndexRouteImport } from './routes/_authenticated/timetable/generate/index'
import { Route as AuthenticatedTimetableAssignIndexRouteImport } from './routes/_authenticated/timetable/assign/index'
import { Route as AuthenticatedSubjectsOfferingsIndexRouteImport } from './routes/_authenticated/subjects/offerings/index'
import { Route as AuthenticatedSubjectsIdIndexRouteImport } from './routes/_authenticated/subjects/$id/index'
import { Route as AuthenticatedStudentsStudentIdIndexRouteImport } from './routes/_authenticated/students/$studentId/index'
import { Route as AuthenticatedHrTeachersIndexRouteImport } from './routes/_authenticated/hr/teachers/index'
import { Route as AuthenticatedHrDepartmentsIndexRouteImport } from './routes/_authenticated/hr/departments/index'
import { Route as AuthenticatedAdminRolesIndexRouteImport } from './routes/_authenticated/admin/roles/index'
import { Route as AuthenticatedAdminImportIndexRouteImport } from './routes/_authenticated/admin/import/index'
import { Route as AuthenticatedAdminAuditLogsIndexRouteImport } from './routes/_authenticated/admin/audit-logs/index'
import { Route as AuthenticatedTimetableSemestersNewRouteImport } from './routes/_authenticated/timetable/semesters/new'
import { Route as AuthenticatedTimetableSemestersIdRouteImport } from './routes/_authenticated/timetable/semesters/$id'
import { Route as AuthenticatedSubjectsIdEditRouteImport } from './routes/_authenticated/subjects/$id/edit'
import { Route as AuthenticatedHrTeachersNewRouteImport } from './routes/_authenticated/hr/teachers/new'
import { Route as AuthenticatedHrDepartmentsNewRouteImport } from './routes/_authenticated/hr/departments/new'
import { Route as AuthenticatedTimetableSchedulesIdIndexRouteImport } from './routes/_authenticated/timetable/schedules/$id/index'
import { Route as AuthenticatedHrTeachersIdIndexRouteImport } from './routes/_authenticated/hr/teachers/$id/index'
import { Route as AuthenticatedHrTeachersIdEditRouteImport } from './routes/_authenticated/hr/teachers/$id/edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRouteRoute =
  AuthenticatedAnalyticsRouteRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimetableIndexRoute =
  AuthenticatedTimetableIndexRouteImport.update({
    id: '/timetable/',
    path: '/timetable/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectsIndexRoute =
  AuthenticatedSubjectsIndexRouteImport.update({
    id: '/subjects/',
    path: '/subjects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrIndexRoute = AuthenticatedHrIndexRouteImport.update({
  id: '/hr/',
  path: '/hr/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpIndexRoute = AuthenticatedHelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGradesIndexRoute =
  AuthenticatedGradesIndexRouteImport.update({
    id: '/grades/',
    path: '/grades/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnrollmentsIndexRoute =
  AuthenticatedEnrollmentsIndexRouteImport.update({
    id: '/enrollments/',
    path: '/enrollments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAnalyticsRouteRoute,
  } as any)
const StudentStudentTranscriptRoute =
  StudentStudentTranscriptRouteImport.update({
    id: '/student/transcript',
    path: '/student/transcript',
    getParentRoute: () => StudentRouteRoute,
  } as any)
const StudentStudentSubjectsRoute = StudentStudentSubjectsRouteImport.update({
  id: '/student/subjects',
  path: '/student/subjects',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentStudentProfileRoute = StudentStudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentStudentDashboardRoute = StudentStudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => StudentRouteRoute,
} as any)
const AuthenticatedSubjectsPrerequisitesRoute =
  AuthenticatedSubjectsPrerequisitesRouteImport.update({
    id: '/subjects/prerequisites',
    path: '/subjects/prerequisites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectsNewRoute =
  AuthenticatedSubjectsNewRouteImport.update({
    id: '/subjects/new',
    path: '/subjects/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimetableSemestersIndexRoute =
  AuthenticatedTimetableSemestersIndexRouteImport.update({
    id: '/timetable/semesters/',
    path: '/timetable/semesters/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimetableSchedulesIndexRoute =
  AuthenticatedTimetableSchedulesIndexRouteImport.update({
    id: '/timetable/schedules/',
    path: '/timetable/schedules/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimetableGenerateIndexRoute =
  AuthenticatedTimetableGenerateIndexRouteImport.update({
    id: '/timetable/generate/',
    path: '/timetable/generate/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimetableAssignIndexRoute =
  AuthenticatedTimetableAssignIndexRouteImport.update({
    id: '/timetable/assign/',
    path: '/timetable/assign/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectsOfferingsIndexRoute =
  AuthenticatedSubjectsOfferingsIndexRouteImport.update({
    id: '/subjects/offerings/',
    path: '/subjects/offerings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectsIdIndexRoute =
  AuthenticatedSubjectsIdIndexRouteImport.update({
    id: '/subjects/$id/',
    path: '/subjects/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsStudentIdIndexRoute =
  AuthenticatedStudentsStudentIdIndexRouteImport.update({
    id: '/students/$studentId/',
    path: '/students/$studentId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrTeachersIndexRoute =
  AuthenticatedHrTeachersIndexRouteImport.update({
    id: '/hr/teachers/',
    path: '/hr/teachers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrDepartmentsIndexRoute =
  AuthenticatedHrDepartmentsIndexRouteImport.update({
    id: '/hr/departments/',
    path: '/hr/departments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRolesIndexRoute =
  AuthenticatedAdminRolesIndexRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminImportIndexRoute =
  AuthenticatedAdminImportIndexRouteImport.update({
    id: '/import/',
    path: '/import/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditLogsIndexRoute =
  AuthenticatedAdminAuditLogsIndexRouteImport.update({
    id: '/audit-logs/',
    path: '/audit-logs/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedTimetableSemestersNewRoute =
  AuthenticatedTimetableSemestersNewRouteImport.update({
    id: '/timetable/semesters/new',
    path: '/timetable/semesters/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimetableSemestersIdRoute =
  AuthenticatedTimetableSemestersIdRouteImport.update({
    id: '/timetable/semesters/$id',
    path: '/timetable/semesters/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectsIdEditRoute =
  AuthenticatedSubjectsIdEditRouteImport.update({
    id: '/subjects/$id/edit',
    path: '/subjects/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrTeachersNewRoute =
  AuthenticatedHrTeachersNewRouteImport.update({
    id: '/hr/teachers/new',
    path: '/hr/teachers/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrDepartmentsNewRoute =
  AuthenticatedHrDepartmentsNewRouteImport.update({
    id: '/hr/departments/new',
    path: '/hr/departments/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimetableSchedulesIdIndexRoute =
  AuthenticatedTimetableSchedulesIdIndexRouteImport.update({
    id: '/timetable/schedules/$id/',
    path: '/timetable/schedules/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrTeachersIdIndexRoute =
  AuthenticatedHrTeachersIdIndexRouteImport.update({
    id: '/hr/teachers/$id/',
    path: '/hr/teachers/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrTeachersIdEditRoute =
  AuthenticatedHrTeachersIdEditRouteImport.update({
    id: '/hr/teachers/$id/edit',
    path: '/hr/teachers/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/subjects/new': typeof AuthenticatedSubjectsNewRoute
  '/subjects/prerequisites': typeof AuthenticatedSubjectsPrerequisitesRoute
  '/student/dashboard': typeof StudentStudentDashboardRoute
  '/student/profile': typeof StudentStudentProfileRoute
  '/student/subjects': typeof StudentStudentSubjectsRoute
  '/student/transcript': typeof StudentStudentTranscriptRoute
  '/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/enrollments/': typeof AuthenticatedEnrollmentsIndexRoute
  '/grades/': typeof AuthenticatedGradesIndexRoute
  '/help/': typeof AuthenticatedHelpIndexRoute
  '/hr/': typeof AuthenticatedHrIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
  '/subjects/': typeof AuthenticatedSubjectsIndexRoute
  '/timetable/': typeof AuthenticatedTimetableIndexRoute
  '/hr/departments/new': typeof AuthenticatedHrDepartmentsNewRoute
  '/hr/teachers/new': typeof AuthenticatedHrTeachersNewRoute
  '/subjects/$id/edit': typeof AuthenticatedSubjectsIdEditRoute
  '/timetable/semesters/$id': typeof AuthenticatedTimetableSemestersIdRoute
  '/timetable/semesters/new': typeof AuthenticatedTimetableSemestersNewRoute
  '/admin/audit-logs/': typeof AuthenticatedAdminAuditLogsIndexRoute
  '/admin/import/': typeof AuthenticatedAdminImportIndexRoute
  '/admin/roles/': typeof AuthenticatedAdminRolesIndexRoute
  '/hr/departments/': typeof AuthenticatedHrDepartmentsIndexRoute
  '/hr/teachers/': typeof AuthenticatedHrTeachersIndexRoute
  '/students/$studentId/': typeof AuthenticatedStudentsStudentIdIndexRoute
  '/subjects/$id/': typeof AuthenticatedSubjectsIdIndexRoute
  '/subjects/offerings/': typeof AuthenticatedSubjectsOfferingsIndexRoute
  '/timetable/assign/': typeof AuthenticatedTimetableAssignIndexRoute
  '/timetable/generate/': typeof AuthenticatedTimetableGenerateIndexRoute
  '/timetable/schedules/': typeof AuthenticatedTimetableSchedulesIndexRoute
  '/timetable/semesters/': typeof AuthenticatedTimetableSemestersIndexRoute
  '/hr/teachers/$id/edit': typeof AuthenticatedHrTeachersIdEditRoute
  '/hr/teachers/$id/': typeof AuthenticatedHrTeachersIdIndexRoute
  '/timetable/schedules/$id/': typeof AuthenticatedTimetableSchedulesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/subjects/new': typeof AuthenticatedSubjectsNewRoute
  '/subjects/prerequisites': typeof AuthenticatedSubjectsPrerequisitesRoute
  '/student/dashboard': typeof StudentStudentDashboardRoute
  '/student/profile': typeof StudentStudentProfileRoute
  '/student/subjects': typeof StudentStudentSubjectsRoute
  '/student/transcript': typeof StudentStudentTranscriptRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/enrollments': typeof AuthenticatedEnrollmentsIndexRoute
  '/grades': typeof AuthenticatedGradesIndexRoute
  '/help': typeof AuthenticatedHelpIndexRoute
  '/hr': typeof AuthenticatedHrIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/subjects': typeof AuthenticatedSubjectsIndexRoute
  '/timetable': typeof AuthenticatedTimetableIndexRoute
  '/hr/departments/new': typeof AuthenticatedHrDepartmentsNewRoute
  '/hr/teachers/new': typeof AuthenticatedHrTeachersNewRoute
  '/subjects/$id/edit': typeof AuthenticatedSubjectsIdEditRoute
  '/timetable/semesters/$id': typeof AuthenticatedTimetableSemestersIdRoute
  '/timetable/semesters/new': typeof AuthenticatedTimetableSemestersNewRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsIndexRoute
  '/admin/import': typeof AuthenticatedAdminImportIndexRoute
  '/admin/roles': typeof AuthenticatedAdminRolesIndexRoute
  '/hr/departments': typeof AuthenticatedHrDepartmentsIndexRoute
  '/hr/teachers': typeof AuthenticatedHrTeachersIndexRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdIndexRoute
  '/subjects/$id': typeof AuthenticatedSubjectsIdIndexRoute
  '/subjects/offerings': typeof AuthenticatedSubjectsOfferingsIndexRoute
  '/timetable/assign': typeof AuthenticatedTimetableAssignIndexRoute
  '/timetable/generate': typeof AuthenticatedTimetableGenerateIndexRoute
  '/timetable/schedules': typeof AuthenticatedTimetableSchedulesIndexRoute
  '/timetable/semesters': typeof AuthenticatedTimetableSemestersIndexRoute
  '/hr/teachers/$id/edit': typeof AuthenticatedHrTeachersIdEditRoute
  '/hr/teachers/$id': typeof AuthenticatedHrTeachersIdIndexRoute
  '/timetable/schedules/$id': typeof AuthenticatedTimetableSchedulesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_student': typeof StudentRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/subjects/new': typeof AuthenticatedSubjectsNewRoute
  '/_authenticated/subjects/prerequisites': typeof AuthenticatedSubjectsPrerequisitesRoute
  '/_student/student/dashboard': typeof StudentStudentDashboardRoute
  '/_student/student/profile': typeof StudentStudentProfileRoute
  '/_student/student/subjects': typeof StudentStudentSubjectsRoute
  '/_student/student/transcript': typeof StudentStudentTranscriptRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/enrollments/': typeof AuthenticatedEnrollmentsIndexRoute
  '/_authenticated/grades/': typeof AuthenticatedGradesIndexRoute
  '/_authenticated/help/': typeof AuthenticatedHelpIndexRoute
  '/_authenticated/hr/': typeof AuthenticatedHrIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
  '/_authenticated/subjects/': typeof AuthenticatedSubjectsIndexRoute
  '/_authenticated/timetable/': typeof AuthenticatedTimetableIndexRoute
  '/_authenticated/hr/departments/new': typeof AuthenticatedHrDepartmentsNewRoute
  '/_authenticated/hr/teachers/new': typeof AuthenticatedHrTeachersNewRoute
  '/_authenticated/subjects/$id/edit': typeof AuthenticatedSubjectsIdEditRoute
  '/_authenticated/timetable/semesters/$id': typeof AuthenticatedTimetableSemestersIdRoute
  '/_authenticated/timetable/semesters/new': typeof AuthenticatedTimetableSemestersNewRoute
  '/_authenticated/admin/audit-logs/': typeof AuthenticatedAdminAuditLogsIndexRoute
  '/_authenticated/admin/import/': typeof AuthenticatedAdminImportIndexRoute
  '/_authenticated/admin/roles/': typeof AuthenticatedAdminRolesIndexRoute
  '/_authenticated/hr/departments/': typeof AuthenticatedHrDepartmentsIndexRoute
  '/_authenticated/hr/teachers/': typeof AuthenticatedHrTeachersIndexRoute
  '/_authenticated/students/$studentId/': typeof AuthenticatedStudentsStudentIdIndexRoute
  '/_authenticated/subjects/$id/': typeof AuthenticatedSubjectsIdIndexRoute
  '/_authenticated/subjects/offerings/': typeof AuthenticatedSubjectsOfferingsIndexRoute
  '/_authenticated/timetable/assign/': typeof AuthenticatedTimetableAssignIndexRoute
  '/_authenticated/timetable/generate/': typeof AuthenticatedTimetableGenerateIndexRoute
  '/_authenticated/timetable/schedules/': typeof AuthenticatedTimetableSchedulesIndexRoute
  '/_authenticated/timetable/semesters/': typeof AuthenticatedTimetableSemestersIndexRoute
  '/_authenticated/hr/teachers/$id/edit': typeof AuthenticatedHrTeachersIdEditRoute
  '/_authenticated/hr/teachers/$id/': typeof AuthenticatedHrTeachersIdIndexRoute
  '/_authenticated/timetable/schedules/$id/': typeof AuthenticatedTimetableSchedulesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/analytics'
    | '/dashboard'
    | '/auth/callback'
    | '/subjects/new'
    | '/subjects/prerequisites'
    | '/student/dashboard'
    | '/student/profile'
    | '/student/subjects'
    | '/student/transcript'
    | '/analytics/'
    | '/enrollments/'
    | '/grades/'
    | '/help/'
    | '/hr/'
    | '/notifications/'
    | '/students/'
    | '/subjects/'
    | '/timetable/'
    | '/hr/departments/new'
    | '/hr/teachers/new'
    | '/subjects/$id/edit'
    | '/timetable/semesters/$id'
    | '/timetable/semesters/new'
    | '/admin/audit-logs/'
    | '/admin/import/'
    | '/admin/roles/'
    | '/hr/departments/'
    | '/hr/teachers/'
    | '/students/$studentId/'
    | '/subjects/$id/'
    | '/subjects/offerings/'
    | '/timetable/assign/'
    | '/timetable/generate/'
    | '/timetable/schedules/'
    | '/timetable/semesters/'
    | '/hr/teachers/$id/edit'
    | '/hr/teachers/$id/'
    | '/timetable/schedules/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/dashboard'
    | '/auth/callback'
    | '/subjects/new'
    | '/subjects/prerequisites'
    | '/student/dashboard'
    | '/student/profile'
    | '/student/subjects'
    | '/student/transcript'
    | '/analytics'
    | '/enrollments'
    | '/grades'
    | '/help'
    | '/hr'
    | '/notifications'
    | '/students'
    | '/subjects'
    | '/timetable'
    | '/hr/departments/new'
    | '/hr/teachers/new'
    | '/subjects/$id/edit'
    | '/timetable/semesters/$id'
    | '/timetable/semesters/new'
    | '/admin/audit-logs'
    | '/admin/import'
    | '/admin/roles'
    | '/hr/departments'
    | '/hr/teachers'
    | '/students/$studentId'
    | '/subjects/$id'
    | '/subjects/offerings'
    | '/timetable/assign'
    | '/timetable/generate'
    | '/timetable/schedules'
    | '/timetable/semesters'
    | '/hr/teachers/$id/edit'
    | '/hr/teachers/$id'
    | '/timetable/schedules/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_student'
    | '/login'
    | '/register'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/auth/callback'
    | '/_authenticated/subjects/new'
    | '/_authenticated/subjects/prerequisites'
    | '/_student/student/dashboard'
    | '/_student/student/profile'
    | '/_student/student/subjects'
    | '/_student/student/transcript'
    | '/_authenticated/analytics/'
    | '/_authenticated/enrollments/'
    | '/_authenticated/grades/'
    | '/_authenticated/help/'
    | '/_authenticated/hr/'
    | '/_authenticated/notifications/'
    | '/_authenticated/students/'
    | '/_authenticated/subjects/'
    | '/_authenticated/timetable/'
    | '/_authenticated/hr/departments/new'
    | '/_authenticated/hr/teachers/new'
    | '/_authenticated/subjects/$id/edit'
    | '/_authenticated/timetable/semesters/$id'
    | '/_authenticated/timetable/semesters/new'
    | '/_authenticated/admin/audit-logs/'
    | '/_authenticated/admin/import/'
    | '/_authenticated/admin/roles/'
    | '/_authenticated/hr/departments/'
    | '/_authenticated/hr/teachers/'
    | '/_authenticated/students/$studentId/'
    | '/_authenticated/subjects/$id/'
    | '/_authenticated/subjects/offerings/'
    | '/_authenticated/timetable/assign/'
    | '/_authenticated/timetable/generate/'
    | '/_authenticated/timetable/schedules/'
    | '/_authenticated/timetable/semesters/'
    | '/_authenticated/hr/teachers/$id/edit'
    | '/_authenticated/hr/teachers/$id/'
    | '/_authenticated/timetable/schedules/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable/': {
      id: '/_authenticated/timetable/'
      path: '/timetable'
      fullPath: '/timetable/'
      preLoaderRoute: typeof AuthenticatedTimetableIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects/': {
      id: '/_authenticated/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof AuthenticatedSubjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/': {
      id: '/_authenticated/hr/'
      path: '/hr'
      fullPath: '/hr/'
      preLoaderRoute: typeof AuthenticatedHrIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help/': {
      id: '/_authenticated/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof AuthenticatedHelpIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grades/': {
      id: '/_authenticated/grades/'
      path: '/grades'
      fullPath: '/grades/'
      preLoaderRoute: typeof AuthenticatedGradesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enrollments/': {
      id: '/_authenticated/enrollments/'
      path: '/enrollments'
      fullPath: '/enrollments/'
      preLoaderRoute: typeof AuthenticatedEnrollmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRouteRoute
    }
    '/_student/student/transcript': {
      id: '/_student/student/transcript'
      path: '/student/transcript'
      fullPath: '/student/transcript'
      preLoaderRoute: typeof StudentStudentTranscriptRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/_student/student/subjects': {
      id: '/_student/student/subjects'
      path: '/student/subjects'
      fullPath: '/student/subjects'
      preLoaderRoute: typeof StudentStudentSubjectsRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/_student/student/profile': {
      id: '/_student/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentStudentProfileRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/_student/student/dashboard': {
      id: '/_student/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentStudentDashboardRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/_authenticated/subjects/prerequisites': {
      id: '/_authenticated/subjects/prerequisites'
      path: '/subjects/prerequisites'
      fullPath: '/subjects/prerequisites'
      preLoaderRoute: typeof AuthenticatedSubjectsPrerequisitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects/new': {
      id: '/_authenticated/subjects/new'
      path: '/subjects/new'
      fullPath: '/subjects/new'
      preLoaderRoute: typeof AuthenticatedSubjectsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable/semesters/': {
      id: '/_authenticated/timetable/semesters/'
      path: '/timetable/semesters'
      fullPath: '/timetable/semesters/'
      preLoaderRoute: typeof AuthenticatedTimetableSemestersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable/schedules/': {
      id: '/_authenticated/timetable/schedules/'
      path: '/timetable/schedules'
      fullPath: '/timetable/schedules/'
      preLoaderRoute: typeof AuthenticatedTimetableSchedulesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable/generate/': {
      id: '/_authenticated/timetable/generate/'
      path: '/timetable/generate'
      fullPath: '/timetable/generate/'
      preLoaderRoute: typeof AuthenticatedTimetableGenerateIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable/assign/': {
      id: '/_authenticated/timetable/assign/'
      path: '/timetable/assign'
      fullPath: '/timetable/assign/'
      preLoaderRoute: typeof AuthenticatedTimetableAssignIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects/offerings/': {
      id: '/_authenticated/subjects/offerings/'
      path: '/subjects/offerings'
      fullPath: '/subjects/offerings/'
      preLoaderRoute: typeof AuthenticatedSubjectsOfferingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects/$id/': {
      id: '/_authenticated/subjects/$id/'
      path: '/subjects/$id'
      fullPath: '/subjects/$id/'
      preLoaderRoute: typeof AuthenticatedSubjectsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/$studentId/': {
      id: '/_authenticated/students/$studentId/'
      path: '/students/$studentId'
      fullPath: '/students/$studentId/'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/teachers/': {
      id: '/_authenticated/hr/teachers/'
      path: '/hr/teachers'
      fullPath: '/hr/teachers/'
      preLoaderRoute: typeof AuthenticatedHrTeachersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/departments/': {
      id: '/_authenticated/hr/departments/'
      path: '/hr/departments'
      fullPath: '/hr/departments/'
      preLoaderRoute: typeof AuthenticatedHrDepartmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/roles/': {
      id: '/_authenticated/admin/roles/'
      path: '/roles'
      fullPath: '/admin/roles/'
      preLoaderRoute: typeof AuthenticatedAdminRolesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/import/': {
      id: '/_authenticated/admin/import/'
      path: '/import'
      fullPath: '/admin/import/'
      preLoaderRoute: typeof AuthenticatedAdminImportIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit-logs/': {
      id: '/_authenticated/admin/audit-logs/'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs/'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/timetable/semesters/new': {
      id: '/_authenticated/timetable/semesters/new'
      path: '/timetable/semesters/new'
      fullPath: '/timetable/semesters/new'
      preLoaderRoute: typeof AuthenticatedTimetableSemestersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable/semesters/$id': {
      id: '/_authenticated/timetable/semesters/$id'
      path: '/timetable/semesters/$id'
      fullPath: '/timetable/semesters/$id'
      preLoaderRoute: typeof AuthenticatedTimetableSemestersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects/$id/edit': {
      id: '/_authenticated/subjects/$id/edit'
      path: '/subjects/$id/edit'
      fullPath: '/subjects/$id/edit'
      preLoaderRoute: typeof AuthenticatedSubjectsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/teachers/new': {
      id: '/_authenticated/hr/teachers/new'
      path: '/hr/teachers/new'
      fullPath: '/hr/teachers/new'
      preLoaderRoute: typeof AuthenticatedHrTeachersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/departments/new': {
      id: '/_authenticated/hr/departments/new'
      path: '/hr/departments/new'
      fullPath: '/hr/departments/new'
      preLoaderRoute: typeof AuthenticatedHrDepartmentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable/schedules/$id/': {
      id: '/_authenticated/timetable/schedules/$id/'
      path: '/timetable/schedules/$id'
      fullPath: '/timetable/schedules/$id/'
      preLoaderRoute: typeof AuthenticatedTimetableSchedulesIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/teachers/$id/': {
      id: '/_authenticated/hr/teachers/$id/'
      path: '/hr/teachers/$id'
      fullPath: '/hr/teachers/$id/'
      preLoaderRoute: typeof AuthenticatedHrTeachersIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/teachers/$id/edit': {
      id: '/_authenticated/hr/teachers/$id/edit'
      path: '/hr/teachers/$id/edit'
      fullPath: '/hr/teachers/$id/edit'
      preLoaderRoute: typeof AuthenticatedHrTeachersIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAuditLogsIndexRoute: typeof AuthenticatedAdminAuditLogsIndexRoute
  AuthenticatedAdminImportIndexRoute: typeof AuthenticatedAdminImportIndexRoute
  AuthenticatedAdminRolesIndexRoute: typeof AuthenticatedAdminRolesIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAuditLogsIndexRoute:
      AuthenticatedAdminAuditLogsIndexRoute,
    AuthenticatedAdminImportIndexRoute: AuthenticatedAdminImportIndexRoute,
    AuthenticatedAdminRolesIndexRoute: AuthenticatedAdminRolesIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedAnalyticsRouteRouteChildren {
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
}

const AuthenticatedAnalyticsRouteRouteChildren: AuthenticatedAnalyticsRouteRouteChildren =
  {
    AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  }

const AuthenticatedAnalyticsRouteRouteWithChildren =
  AuthenticatedAnalyticsRouteRoute._addFileChildren(
    AuthenticatedAnalyticsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAnalyticsRouteRoute: typeof AuthenticatedAnalyticsRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSubjectsNewRoute: typeof AuthenticatedSubjectsNewRoute
  AuthenticatedSubjectsPrerequisitesRoute: typeof AuthenticatedSubjectsPrerequisitesRoute
  AuthenticatedEnrollmentsIndexRoute: typeof AuthenticatedEnrollmentsIndexRoute
  AuthenticatedGradesIndexRoute: typeof AuthenticatedGradesIndexRoute
  AuthenticatedHelpIndexRoute: typeof AuthenticatedHelpIndexRoute
  AuthenticatedHrIndexRoute: typeof AuthenticatedHrIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
  AuthenticatedSubjectsIndexRoute: typeof AuthenticatedSubjectsIndexRoute
  AuthenticatedTimetableIndexRoute: typeof AuthenticatedTimetableIndexRoute
  AuthenticatedHrDepartmentsNewRoute: typeof AuthenticatedHrDepartmentsNewRoute
  AuthenticatedHrTeachersNewRoute: typeof AuthenticatedHrTeachersNewRoute
  AuthenticatedSubjectsIdEditRoute: typeof AuthenticatedSubjectsIdEditRoute
  AuthenticatedTimetableSemestersIdRoute: typeof AuthenticatedTimetableSemestersIdRoute
  AuthenticatedTimetableSemestersNewRoute: typeof AuthenticatedTimetableSemestersNewRoute
  AuthenticatedHrDepartmentsIndexRoute: typeof AuthenticatedHrDepartmentsIndexRoute
  AuthenticatedHrTeachersIndexRoute: typeof AuthenticatedHrTeachersIndexRoute
  AuthenticatedStudentsStudentIdIndexRoute: typeof AuthenticatedStudentsStudentIdIndexRoute
  AuthenticatedSubjectsIdIndexRoute: typeof AuthenticatedSubjectsIdIndexRoute
  AuthenticatedSubjectsOfferingsIndexRoute: typeof AuthenticatedSubjectsOfferingsIndexRoute
  AuthenticatedTimetableAssignIndexRoute: typeof AuthenticatedTimetableAssignIndexRoute
  AuthenticatedTimetableGenerateIndexRoute: typeof AuthenticatedTimetableGenerateIndexRoute
  AuthenticatedTimetableSchedulesIndexRoute: typeof AuthenticatedTimetableSchedulesIndexRoute
  AuthenticatedTimetableSemestersIndexRoute: typeof AuthenticatedTimetableSemestersIndexRoute
  AuthenticatedHrTeachersIdEditRoute: typeof AuthenticatedHrTeachersIdEditRoute
  AuthenticatedHrTeachersIdIndexRoute: typeof AuthenticatedHrTeachersIdIndexRoute
  AuthenticatedTimetableSchedulesIdIndexRoute: typeof AuthenticatedTimetableSchedulesIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAnalyticsRouteRoute:
    AuthenticatedAnalyticsRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSubjectsNewRoute: AuthenticatedSubjectsNewRoute,
  AuthenticatedSubjectsPrerequisitesRoute:
    AuthenticatedSubjectsPrerequisitesRoute,
  AuthenticatedEnrollmentsIndexRoute: AuthenticatedEnrollmentsIndexRoute,
  AuthenticatedGradesIndexRoute: AuthenticatedGradesIndexRoute,
  AuthenticatedHelpIndexRoute: AuthenticatedHelpIndexRoute,
  AuthenticatedHrIndexRoute: AuthenticatedHrIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
  AuthenticatedSubjectsIndexRoute: AuthenticatedSubjectsIndexRoute,
  AuthenticatedTimetableIndexRoute: AuthenticatedTimetableIndexRoute,
  AuthenticatedHrDepartmentsNewRoute: AuthenticatedHrDepartmentsNewRoute,
  AuthenticatedHrTeachersNewRoute: AuthenticatedHrTeachersNewRoute,
  AuthenticatedSubjectsIdEditRoute: AuthenticatedSubjectsIdEditRoute,
  AuthenticatedTimetableSemestersIdRoute:
    AuthenticatedTimetableSemestersIdRoute,
  AuthenticatedTimetableSemestersNewRoute:
    AuthenticatedTimetableSemestersNewRoute,
  AuthenticatedHrDepartmentsIndexRoute: AuthenticatedHrDepartmentsIndexRoute,
  AuthenticatedHrTeachersIndexRoute: AuthenticatedHrTeachersIndexRoute,
  AuthenticatedStudentsStudentIdIndexRoute:
    AuthenticatedStudentsStudentIdIndexRoute,
  AuthenticatedSubjectsIdIndexRoute: AuthenticatedSubjectsIdIndexRoute,
  AuthenticatedSubjectsOfferingsIndexRoute:
    AuthenticatedSubjectsOfferingsIndexRoute,
  AuthenticatedTimetableAssignIndexRoute:
    AuthenticatedTimetableAssignIndexRoute,
  AuthenticatedTimetableGenerateIndexRoute:
    AuthenticatedTimetableGenerateIndexRoute,
  AuthenticatedTimetableSchedulesIndexRoute:
    AuthenticatedTimetableSchedulesIndexRoute,
  AuthenticatedTimetableSemestersIndexRoute:
    AuthenticatedTimetableSemestersIndexRoute,
  AuthenticatedHrTeachersIdEditRoute: AuthenticatedHrTeachersIdEditRoute,
  AuthenticatedHrTeachersIdIndexRoute: AuthenticatedHrTeachersIdIndexRoute,
  AuthenticatedTimetableSchedulesIdIndexRoute:
    AuthenticatedTimetableSchedulesIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface StudentRouteRouteChildren {
  StudentStudentDashboardRoute: typeof StudentStudentDashboardRoute
  StudentStudentProfileRoute: typeof StudentStudentProfileRoute
  StudentStudentSubjectsRoute: typeof StudentStudentSubjectsRoute
  StudentStudentTranscriptRoute: typeof StudentStudentTranscriptRoute
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentStudentDashboardRoute: StudentStudentDashboardRoute,
  StudentStudentProfileRoute: StudentStudentProfileRoute,
  StudentStudentSubjectsRoute: StudentStudentSubjectsRoute,
  StudentStudentTranscriptRoute: StudentStudentTranscriptRoute,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  StudentRouteRoute: StudentRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
