// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CoreEvent struct {
	ID            int64              `json:"id"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	AggregateType string             `json:"aggregate_type"`
	EventType     string             `json:"event_type"`
	Version       int32              `json:"version"`
	Data          []byte             `json:"data"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type CoreModuleRegistry struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Version         string             `json:"version"`
	GrpcAddress     string             `json:"grpc_address"`
	HealthStatus    string             `json:"health_status"`
	RegisteredAt    pgtype.Timestamptz `json:"registered_at"`
	LastHealthCheck pgtype.Timestamptz `json:"last_health_check"`
}

type CoreSnapshot struct {
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	AggregateType string             `json:"aggregate_type"`
	Version       int32              `json:"version"`
	Data          []byte             `json:"data"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type CoreUser struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	Role         string             `json:"role"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
