// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: modules.sql

package sqlc

import (
	"context"
)

const getModuleByName = `-- name: GetModuleByName :one
SELECT id, name, version, grpc_address, health_status, registered_at, last_health_check FROM core.module_registry WHERE name = $1
`

func (q *Queries) GetModuleByName(ctx context.Context, name string) (CoreModuleRegistry, error) {
	row := q.db.QueryRow(ctx, getModuleByName, name)
	var i CoreModuleRegistry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.GrpcAddress,
		&i.HealthStatus,
		&i.RegisteredAt,
		&i.LastHealthCheck,
	)
	return i, err
}

const listModules = `-- name: ListModules :many
SELECT id, name, version, grpc_address, health_status, registered_at, last_health_check FROM core.module_registry ORDER BY name
`

func (q *Queries) ListModules(ctx context.Context) ([]CoreModuleRegistry, error) {
	rows, err := q.db.Query(ctx, listModules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreModuleRegistry
	for rows.Next() {
		var i CoreModuleRegistry
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.GrpcAddress,
			&i.HealthStatus,
			&i.RegisteredAt,
			&i.LastHealthCheck,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerModule = `-- name: RegisterModule :one
INSERT INTO core.module_registry (name, version, grpc_address, health_status)
VALUES ($1, $2, $3, 'healthy')
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    grpc_address = EXCLUDED.grpc_address,
    health_status = 'healthy',
    last_health_check = NOW()
RETURNING id, name, version, grpc_address, health_status, registered_at, last_health_check
`

type RegisterModuleParams struct {
	Name        string `json:"name"`
	Version     string `json:"version"`
	GrpcAddress string `json:"grpc_address"`
}

func (q *Queries) RegisterModule(ctx context.Context, arg RegisterModuleParams) (CoreModuleRegistry, error) {
	row := q.db.QueryRow(ctx, registerModule, arg.Name, arg.Version, arg.GrpcAddress)
	var i CoreModuleRegistry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.GrpcAddress,
		&i.HealthStatus,
		&i.RegisteredAt,
		&i.LastHealthCheck,
	)
	return i, err
}

const unregisterModule = `-- name: UnregisterModule :exec
DELETE FROM core.module_registry WHERE name = $1
`

func (q *Queries) UnregisterModule(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, unregisterModule, name)
	return err
}

const updateModuleHealth = `-- name: UpdateModuleHealth :exec
UPDATE core.module_registry
SET health_status = $2, last_health_check = NOW()
WHERE name = $1
`

type UpdateModuleHealthParams struct {
	Name         string `json:"name"`
	HealthStatus string `json:"health_status"`
}

func (q *Queries) UpdateModuleHealth(ctx context.Context, arg UpdateModuleHealthParams) error {
	_, err := q.db.Exec(ctx, updateModuleHealth, arg.Name, arg.HealthStatus)
	return err
}
