// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CoreUser, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetModuleByName(ctx context.Context, name string) (CoreModuleRegistry, error)
	GetUserByEmail(ctx context.Context, email string) (CoreUser, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (CoreUser, error)
	ListModules(ctx context.Context) ([]CoreModuleRegistry, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]CoreUser, error)
	RegisterModule(ctx context.Context, arg RegisterModuleParams) (CoreModuleRegistry, error)
	UnregisterModule(ctx context.Context, name string) error
	UpdateModuleHealth(ctx context.Context, arg UpdateModuleHealthParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (CoreUser, error)
}

var _ Querier = (*Queries)(nil)
